* Personal information

#+BEGIN_SRC emacs-lisp
  (setq user-full-name "Nicolas Chapon"
        user-mail-address "nchapon@gmail.com")
#+END_SRC

* Packages
Use package default configuration
#+BEGIN_SRC emacs-lisp
(setq use-package-verbose t)
(setq use-package-always-ensure t)
(require 'use-package)
(use-package auto-compile
  :config (auto-compile-on-load-mode))
#+END_SRC

* Appearence & behavior

** Font
Use Source code Pro font if present

#+BEGIN_SRC emacs-lisp
  (defun my/setup-x11-fonts ()
    (interactive)
    (when (eq window-system 'x)
      (cond
       ((find-font (font-spec :name "Source Code Pro"))
        (set-frame-font "Source Code Pro-14" nil t))
       ((find-font (font-spec :name "DejaVu Sans Mono-12"))
        (set-frame-font "DejaVu Sans Mono-12" nil t)))
      ))

  (when (eq window-system 'x)
    (add-hook 'after-init-hook #'my/setup-x11-fonts))
#+END_SRC

** Mode line
#+BEGIN_SRC emacs-lisp
(use-package smart-mode-line)
#+END_SRC

** Theme
Using moe theme light in the day and dark in the night..
   #+BEGIN_SRC emacs-lisp
     (use-package color-theme)
     (use-package moe-theme
       :config
       (progn
         (setq moe-light-pure-white-background-in-terminal t)

         (moe-light)

         (use-package moe-theme-switcher
             :ensure moe-theme)

         (use-package powerline
           :config
           (powerline-moe-theme))))

   #+END_SRC
** Answering just 'y' or 'n'

#+BEGIN_SRC emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC

** Transparently open compressed files

#+BEGIN_SRC emacs-lisp
(auto-compression-mode t)
#+END_SRC

** Always display line and column numbers
#+BEGIN_SRC emacs-lisp
(setq line-number-mode t)
(setq column-number-mode t)
#+END_SRC
** Windows configuration
*** No menu and toolbar

#+BEGIN_SRC emacs-lisp
(if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
(if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
#+END_SRC

*** No welcome screen

#+BEGIN_SRC emacs-lisp
(setq  inhibit-startup-message t)
#+END_SRC

** Which key

#+BEGIN_SRC emacs-lisp
(use-package which-key
    :config
    (which-key-mode))
#+END_SRC

** Make fringe smaller

#+BEGIN_SRC emacs-lisp
(if (fboundp 'fringe-mode)
    (fringe-mode 4))
#+END_SRC

* General configuration
** Backups
Autosaves and backups are in =<emacs-directory>/tmp=
   #+BEGIN_SRC emacs-lisp
   (setq
 tmp-dir      (file-name-as-directory (concat user-emacs-directory "tmp"))
 autosaves-dir(file-name-as-directory (concat tmp-dir  "autosaves"))
 backups-dir  (file-name-as-directory (concat tmp-dir  "backups")))
   #+END_SRC

Write backup file to own directory

#+BEGIN_SRC emacs-lisp
(setq backup-directory-alist
      `(("." . ,(expand-file-name backups-dir))))
#+END_SRC

** History
Delete old versions

#+BEGIN_SRC emacs-lisp
(setq delete-old-versions t
  kept-new-versions 6
  kept-old-versions 2
  version-control t)
#+END_SRC

** Sane settings

#+BEGIN_SRC emacs-lisp
(setq initial-major-mode 'lisp-interaction-mode
      redisplay-dont-pause t
      column-number-mode t
      echo-keystrokes 0.02
      transient-mark-mode t
      shift-select-mode nil
      require-final-newline t
      truncate-partial-width-windows nil
      delete-by-moving-to-trash t
      confirm-nonexistent-file-or-buffer nil
      query-replace-highlight t)
#+END_SRC

** Dired
*** Always delete and copy recursively
#+BEGIN_SRC emacs-lisp
(setq dired-recursive-delete 'always)
(setq dired-recursive-copy 'always)
#+END_SRC
*** Dired-x
Enable C-x C-j
#+BEGIN_SRC emacs-lisp
(add-hook 'dired-load-hook
            (function (lambda () (load "dired-x"))))
#+END_SRC

** Undo Tree
This lets you use =C-x u= (=undo-tree-visualize=)
#+BEGIN_SRC emacs-lisp
(use-package undo-tree
  :diminish undo-tree-mode
  :config
  (progn
    (global-undo-tree-mode)
    (setq undo-tree-visualizer-timestamps t)
    (setq undo-tree-visualizer-diff t)))
#+END_SRC

** UTF-8
Set all coding systems to utf-8
#+BEGIN_SRC emacs-lisp
(prefer-coding-system 'utf-8-unix)
(set-clipboard-coding-system 'utf-8-unix)
(set-default-coding-systems 'utf-8-unix)
(set-keyboard-coding-system 'utf-8-unix)
(set-language-environment 'utf-8)
(set-selection-coding-system 'utf-8-unix)
(set-terminal-coding-system 'utf-8-unix)
(setq locale-coding-system 'utf-8-unix)
(setq coding-system-for-write 'utf-8-unix)
(setq default-buffer-file-coding-system 'utf-8-unix)
(setq default-process-coding-system '(utf-8-unix . utf-8-unix))
(setq file-name-coding-system  'utf-8)
(add-to-list 'auto-coding-alist '("." . utf-8))
#+END_SRC
** Indentation & Tabs
*** Default indentation
Always spaces with width of 4
#+BEGIN_SRC emacs-lisp
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
#+END_SRC
*** Indent new line if necessary
#+BEGIN_SRC emacs-lisp
(define-key global-map (kbd "RET") 'newline-and-indent)
#+END_SRC
** Cleanup before save
Remove all trailing whitespace and trailing blank lines before saving the file
#+BEGIN_SRC emacs-lisp
(add-hook 'before-save-hook 'whitespace-cleanup)
#+END_SRC
** Lines should be 80 characters
#+BEGIN_SRC emacs-lisp
(setq fill-column 80)
#+END_SRC
** Buffers
*** Uniquify
Use file path to ensure buffer name uniqueness

#+BEGIN_SRC emacs-lisp
(require 'uniquify)
(setq uniquify-buffer-name-style 'forward)
(setq uniquify-separator "/")
(setq uniquify-after-kill-buffer-p t)
(setq uniquify-ignore-buffers-re "^\\*")
#+END_SRC

*** Auto refresh buffers
#+BEGIN_SRC emacs-lisp
(global-auto-revert-mode 1)
#+END_SRC

Also auto refresh dired, but be quiet about it

#+BEGIN_SRC emacs-lisp
(setq global-auto-revert-non-file-buffers t)
#+END_SRC

*** Rename file and buffer
#+BEGIN_SRC emacs-lisp
(defun nc/rename-file-and-buffer ()
  "Renames current buffer and file it is visiting."
  (interactive)
  (let ((filename (buffer-file-name)))
    (if (not (and filename (file-exists-p filename)))
        (message "Buffer is not visiting a file!")
      (let ((new-name (read-file-name "New name: " filename)))
        (cond
         ((vc-backend filename) (vc-rename-file filename new-name))
         (t
          (rename-file filename new-name t)
          (set-visited-file-name new-name t t)))))))
#+END_SRC

*** Delete file and buffer

#+BEGIN_SRC emacs-lisp
(defun nc/delete-file-and-buffer ()
  "Kill the current buffer and deletes the file it is visiting."
  (interactive)
  (let ((filename (buffer-file-name)))
    (when filename
      (if (vc-backend filename)
          (vc-delete-file filename)
        (when (y-or-n-p (format "Are you sure you want to delete %s? " filename))
          (delete-file filename)
          (message "Deleted file %s" filename)
          (kill-buffer))))))
#+END_SRC

* Project management
** Projectile
#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :diminish projectile-mode
    :init (progn
            (setq projectile-keymap-prefix (kbd "C-c p"))
            (setq projectile-enable-caching t))

    :config
    (add-to-list 'projectile-globally-ignored-directories "elpa")
    (add-to-list 'projectile-globally-ignored-directories "target")
    (add-to-list 'projectile-globally-ignored-directories ".cache")
    (add-to-list 'projectile-globally-ignored-directories "image-dired")
    (add-to-list 'projectile-globally-ignored-files "node_modules")
    (projectile-global-mode))

#+END_SRC

** Custom mode line indicator

#+BEGIN_SRC emacs-lisp
(setq projectile-mode-line '(:eval (format " Proj[%s]" (projectile-project-name))))
#+END_SRC
* Completion, matching and suggestions
** Company
Standard auto completion mode.
#+BEGIN_SRC emacs-lisp
  (use-package company
    :defer t
    :diminish ""
    :bind ("C-." . company-complete)
    :init (global-company-mode)
    :config
    (progn
      (setq company-idle-delay 0.1
            ;; min prefix of 1 chars
            company-minimum-prefix-length 1
            company-selection-wrap-around t
            company-show-numbers t
            company-dabbrev-downcase nil
            company-dabbrev-code-everywhere t
            company-transformers '(company-sort-by-occurrence))
      (bind-keys :map company-active-map
                 ("C-n" . company-select-next)
                 ("C-p" . company-select-previous)
                 ("C-d" . company-show-doc-buffer)
                 ("<tab>" . company-complete))))

#+END_SRC
** Helm
*** Helm core configuration
#+BEGIN_SRC emacs-lisp
  (use-package helm
    :diminish helm-mode

    :config (setq helm-idle-delay 0.0 ; update fast sources immediately (doesn't).
                  helm-input-idle-delay 0.01  ; this actually updates things
                                          ; reeeelatively quickly.
                  helm-yas-display-key-on-candidate t
                  helm-quick-update t
                  helm-split-window-in-side-p t
                  helm-buffers-fuzzy-matching t
                  helm-move-to-line-cycle-in-source t
                  helm-ff-search-library-in-sexp t
                  helm-ff-file-name-history-use-recentf t
                  helm-M-x-requires-pattern nil
                  helm-ff-skip-boring-files t
                  helm-for-files-preferred-list (quote (helm-source-files-in-current-dir helm-source-recentf helm-source-bookmarks helm-source-file-cache helm-source-buffers-list helm-source-locate helm-source-ls-git)))

    :init (progn
            (require 'helm-config)
            (helm-mode t)

            (use-package helm-projectile)
            (helm-projectile-on))

    :bind (("C-x b" . helm-mini)
           ("M-x" . helm-M-x)
           ("C-x C-f" . helm-find-files)
           ("C-h f" . helm-apropos)
           ("C-x C-b" . helm-buffers-list)
           ("M-y" . helm-show-kill-ring)
           ("M-x" . helm-M-x)
           ("C-x c o" . helm-occur)
           ("C-x c s" . helm-swoop)
           ("C-x C-r" . helm-recentf)
           ("C-x c y" . helm-yas-complete)
           ("C-x c Y" . helm-yas-create-snippet-on-region)
           ("C-x c SPC" . helm-all-mark-rings)))
#+END_SRC
*** helm-ag
Can integrate Helm with [[https://github.com/ggreer/the_silver_searcher][The Silver Searcher]] (ag A code searching tool similar to ack, with a focus on speed.)


#+BEGIN_SRC emacs-lisp
(use-package helm-ag)
#+END_SRC
*** helm-tramp
Display server list from your =~/.ssh/config= with helm interface
#+begin_src emacs-lisp :tangle yes
  (use-package helm-tramp)
#+end_src

Set tramp default method to ssh

#+begin_src emacs-lisp
(setq tramp-default-method "ssh")
#+end_src

** Hippie expand
Configuration
#+BEGIN_SRC emacs-lisp
(setq hippie-expand-try-functions-list
  '(try-complete-file-name-partially
    try-complete-file-name
    try-expand-all-abbrevs
    try-expand-dabbrev
    try-expand-dabbrev-visible
    try-expand-dabbrev-all-buffers
    try-expand-dabbrev-from-kill
    try-complete-lisp-symbol-partially
    try-complete-lisp-symbol))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(bind-key "M-/" 'hippie-expand)
#+END_SRC

* Navigation
** Move to beginning of file
From  [[https://github.com/bbatsov/prelude]]
See article [[http://emacsredux.com/blog/2013/05/22/smarter-navigation-to-the-beginning-of-a-line/]]
#+BEGIN_SRC emacs-lisp
(defun smarter-move-beginning-of-line (arg)
  "Move point back to indentation of beginning of line.

Move point to the first non-whitespace character on this line.
If point is already there, move to the beginning of the line.
Effectively toggle between the first non-whitespace character and
the beginning of the line.

If ARG is not nil or 1, move forward ARG - 1 lines first.  If
point reaches the beginning or end of the buffer, stop there."
  (interactive "^p")
  (setq arg (or arg 1))

  ;; Move lines first
  (when (/= arg 1)
    (let ((line-move-visual nil))
      (forward-line (1- arg))))

  (let ((orig-point (point)))
    (back-to-indentation)
    (when (= orig-point (point))
      (move-beginning-of-line 1))))

(global-set-key [remap move-beginning-of-line]
                'smarter-move-beginning-of-line)

#+END_SRC
** Ace jump mode
Should I try avy ?
   :PROPERTIES:
   :ORDERED:  t
   :END:
#+BEGIN_SRC emacs-lisp
  (use-package ace-jump-mode
    :bind
    (("C-c /" . ace-jump-mode)
     ("C-c k". ace-jump-mode-pop-mark)))
#+END_SRC
** Ace window
#+BEGIN_SRC emacs-lisp
  (use-package ace-window
    :bind (([remap other-window] . ace-window))
    :config
    (setq aw-keys '(?q ?s ?d ?f ?g ?h ?j ?k ?l))
    ;; increase size face
    (custom-set-faces
     '(aw-leading-char-face
       ((t (:inherit ace-jump-face-foreground :height 3.0))))))
#+END_SRC
* Org
** My files
*** Base directory
#+begin_src emacs-lisp
  (defvar nc/org-notes-directory "~/notes")

  (defun nc/expand-org-notes-path (path)
      "Expand org-notes-directory with PATH"
      (expand-file-name (concat nc/org-notes-directory "/" path)))
#+end_src
** Org global keys

#+BEGIN_SRC emacs-lisp
(bind-key "\C-cl" 'org-store-link)
(bind-key "\C-cc" 'org-capture)
(bind-key "\C-ca" 'org-agenda)
(bind-key "\C-cb" 'org-iswitchb)
#+END_SRC

** Modules
*** Bullet Module
#+BEGIN_SRC emacs-lisp
(use-package org-bullets
    :config
    (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+END_SRC

Hiding leading bullets in headers

#+begin_src emacs-lisp
  (setq org-hide-leading-stars t)
#+end_src

** Tasks
*** Todo tasks
**** Todo states
 - parentheses indicate keyboard shortcuts
 - =@= prompts for a note
 - =!= logs the timestamp of the state change

#+BEGIN_SRC emacs-lisp
(setq org-todo-keywords
      (quote ((sequence "TODO(t)"
                        "NEXT(n)"
                        "STARTED(s)"
                        "WAITING(w@/!)"
                        "SOMEDAY(.)" "|" "DONE(d!)" "CANCELLED(c@/!)")
              (sequence "MEETING(m)" "RDV(r)" "FORMATION(f)" "PHONE(p)" "|" "DONE(d)"))))

#+END_SRC

**** Todo faces
#+BEGIN_SRC emacs-lisp
(setq org-todo-keyword-faces
      (quote (("TODO" :foreground "red" :weight bold)
              ("NEXT" :foreground "blue" :weight bold)
              ("STARTED" :foreground "orange" :weight bold)
              ("SOMEDAY" :foreground "dark gray" :weight bold)
              ("DONE" :foreground "forest green" :weight bold)
              ("WAITING" :foreground "magenta" :weight bold)
              ("MEETING" :foreground "cyan" :weight bold)
              ("RDV" :foreground "cyan" :weight bold)
              ("FORMATION" :foreground "khaki" :weight bold)
              ("CANCELLED" :foreground "forest green" :weight bold))))
#+END_SRC
*** Projects

#+begin_src emacs-lisp
(setq org-tags-exclude-from-inheritance '("PROJECT"))
#+end_src
** Org-clock
*** Function for clocking in
#+begin_src emacs-lisp
(defun my/org-clock-in ()
  (interactive)
  (org-clock-in '(4)))

(global-set-key (kbd "<f11>") #'my/org-clock-in)
(global-set-key (kbd "C-<f11>") 'org-clock-out)
#+end_src
*** Configuration

Too many clock entries clutter up a heading.

#+begin_src emacs-lisp
  (use-package org
    :bind (("C-c C-x C-i" . my/org-clock-in)
           ("C-c C-x C-o" . org-clock-out))
    :config
    (progn
      ;; Insinuate it everywhere
      (org-clock-persistence-insinuate)
      ;; Show lot of clocking history so it's easy to pick items off the C-F11 list
      (setq org-clock-history-length 23
            ;; Resume clocking task on clock-in if the clock is open
            org-clock-in-resume t
            ;; Separate drawers for clocking and logs
            org-drawers '("PROPERTIES" "CLOCK" "LOGBOOK" "RESULTS" "HIDDEN")
            ;; Save clock data and state changes and notes in the LOGBOOK drawer
            org-clock-into-drawer t
            ;; Sometimes I change tasks I'm clocking quickly -
            ;; this removes clocked tasks with 0:00 duration
            org-clock-out-remove-zero-time-clocks t
            ;; Clock out when moving task to a done state
            org-clock-out-when-done t
            ;; Save the running clock and all clock history when exiting Emacs, load it on startup
            org-clock-persist t
            ;; Prompt to resume an active clock
            org-clock-persist-query-resume t
            ;; Enable auto clock resolution for finding open clocks
            org-clock-auto-clock-resolution #'when-no-clock-is-running
            ;; Include current clocking task in clock reports
            org-clock-report-include-clocking-task t)))
#+end_src

*** Timereport indentation
Fix timereport indentation

#+begin_src emacs-lisp
(defun my-org-clocktable-indent-string (level)
  (if (= level 1)
      ""
    (let ((str "\\"))
      (while (> level 2)
        (setq level (1- level)
              str (concat str "_")))
      (concat str "_ "))))

(advice-add 'org-clocktable-indent-string :override #'my-org-clocktable-indent-string)
#+end_src
*** Clock in organization task as default
Organization task ID
#+begin_src emacs-lisp
(defvar my/organization-task-id "93905237-907b-42a6-bdb1-11832c4d59d5")
#+end_src

This clocks in a predefined task by org-id that is the default task to clock in
#+begin_src emacs-lisp :tangle yes
  (use-package org-id
    :ensure org
    :config
    (defun my/clock-in-organization-task-as-default ()
      (interactive)
      (org-with-point-at (org-id-find my/organization-task-id 'marker)
        (org-clock-in '(16)))))
#+end_src

** Agenda
*** TODO Agenda configuration
#+BEGIN_SRC emacs-lisp
  (setq org-agenda-files (list "~/notes/GTD")
        org-agenda-span 2
        org-agenda-start-on-weekday nil
        org-agenda-skip-deadline-if-done t
        org-agenda-skip-scheduled-if-done t
        org-deadline-warning-days 5)
#+END_SRC
*** Diary
#+BEGIN_SRC emacs-lisp
  (setq diary-file "~/notes/diary"
        org-agenda-include-diary t)
#+END_SRC
*** Agenda commands
Function to skip headline tagged with =:PROJECT:=

#+begin_src emacs-lisp
(defun my/org-agenda-skip-project ()
    (org-agenda-skip-entry-if 'regexp ":PROJECT:"))
#+end_src


My commands

    #+BEGIN_SRC emacs-lisp
      (setq org-agenda-custom-commands
            '((" " "Agenda"
               ((agenda "" ((org-agenda-sorting-strategy '(timestamp-up time-up priority-down category-keep))))
                (tags "REFILE"
                      ((org-agenda-overriding-header "Tasks to Refile")
                       (org-tags-match-list-sublevels nil)))
                (tags-todo "TODO=\"STARTED\""
                           ((org-agenda-overriding-header "Started tasks")
                            (org-agenda-sorting-strategy '(priority-down todo-state-up category-keep))))
                (tags-todo "TODO=\"NEXT\"+@cnp"
                           ((org-agenda-overriding-header "Next tasks @office")
                            (org-tags-exclude-from-inheritance '("PROJECT"))
                            (org-agenda-sorting-strategy '(priority-down todo-state-up category-keep))))
                (tags-todo "TODO=\"TODO\"+tasks"
                           ((org-agenda-overriding-header "Other tasks")
                            (org-tags-exclude-from-inheritance '("PROJECT"))
                            (org-agenda-sorting-strategy '(priority-down todo-state-up category-keep))))
                )
               nil)
              ("o" tags-todo "@cnp-MEETING"
               ((org-agenda-overriding-header "Office tasks")
                (org-tags-exclude-from-inheritance '("PROJECT"))
                (org-agenda-skip-function 'my/org-agenda-skip-project)
                (org-agenda-sorting-strategy '(priority-down todo-state-up category-keep))))
              ("r" "Tasks to Refile" tags "REFILE"
               ((org-agenda-overriding-header "Tasks to Refile")
                (org-tags-match-list-sublevels nil)))
              ("W" "To See" tags "@watching"
               ((org-agenda-overriding-header "To See")
                (org-tags-match-list-sublevels 'indented)))
              ("R" "To Read" tags-todo "@reading"
               ((org-agenda-overriding-header "To Read")
                (org-tags-match-list-sublevels 'indented)))
              ("w" "Waiting Tasks" tags-todo "-CANCELLED/!WAITING|HOLD"
               ((org-agenda-overriding-header "Waiting and Postponed Tasks")))
              ("d" "Timeline for today" ((agenda "" ))
               ((org-agenda-ndays 1)
                (org-agenda-show-log t)
                (org-agenda-log-mode-items '(clock closed))
                (org-agenda-clockreport-mode t)
                (org-agenda-entry-types '())))
              ("S" tags-todo "TODO=\"STARTED\""
               ((org-agenda-overriding-header "All started tasks")
                (org-agenda-sorting-strategy '(priority-down todo-state-up category-keep))))
              ("Z" "Weekly review" agenda ""
               ((org-agenda-span 7)
                (org-agenda-log-mode 1)))))
    #+END_SRC

** Taking notes
*** My templates
#+begin_src emacs-lisp
  (setq org-capture-templates
        '(("t" "todo" entry (file (nc/expand-org-notes-path "GTD/refile.org"))
           "* TODO %?\n%U\n%a\n" :clock-in t :clock-resume t)
          ("n" "Next Task" entry (file+headline (nc/expand-org-notes-path "GTD/refile.org") "Tasks")
           "** NEXT %? \nDEADLINE: %t")
          ("s" "Someday / Maybe" entry (file+headline (nc/expand-org-notes-path "GTD/refile.org") "Someday / Maybe")
            "* SOMEDAY %? :IDEA:\n%u" :clock-in t :clock-resume t)
          ("f" "FishLog" plain (file+datetree+prompt (nc/expand-org-notes-path "GTD/fishlog.org"))
           "%[~/notes/templates/fishlog.org]")
          ("F" "Film" entry (file+headline (nc/expand-org-notes-path "GTD/watching.org") "Films à voir")
               "* NEXT %^{Titre}
       %i
       - *Réalisateur:* %^{Auteur}
       - *Année:* %^{année}
       - *Genre:* %^{genre}

      %?

      %U" :prepend t)
          ("N" "Note" entry (file+headline (nc/expand-org-notes-path "GTD/refile.org") "Notes")
           "* %? :NOTE:\n%U\n%a\n" :clock-in t :clock-resume t)
          ("i" "Interrupting task" entry
             (file+datetree (nc/expand-org-notes-path "GTD/diary.org"))
             "* %^{Task}"
             :clock-in t :clock-resume t)
          ("m" "Meeting" entry (file (nc/expand-org-notes-path "GTD/refile.org"))
           "* MEETING %? :MEETING:\n%U\nSCHEDULED: %(org-insert-time-stamp (org-read-date nil t \"+0d\"))\n")
          ("p" "Phone call" entry (file (nc/expand-org-notes-path "GTD/refile.org"))
                 "* PHONE %? :PHONE:\n%U" :clock-in t :clock-resume t)
          ("a" "RendezVous" entry (file (nc/expand-org-notes-path "GTD/refile.org"))
                 "* RDV %? :APPT:\n%U\nSCHEDULED: %(org-insert-time-stamp (org-read-date nil t \"+0d\"))\n")
          ("j" "Journal" entry (file+datetree (nc/expand-org-notes-path "GTD/journal.org"))
           "* %?\nEntered on %U\n  %i\n  %a")
          ("w" "WeeklyReview" entry (file+datetree+prompt (nc/expand-org-notes-path "GTD/weekly-review.org"))
           "* Summary of the week :REVIEW:\n%[~/notes/templates/review.org]")
          ))
#+end_src
**** Speed Key for interruption task
Key =F9= capture interruption task
#+begin_src emacs-lisp
(defun my/capture-interruption-task ()
    "Interrupted Task"
    (interactive)
    (org-capture 4 "i"))

;; Override the key definition
(global-set-key (kbd "<f9>") 'my/capture-interruption-task)
#+end_src

*** Refiling
Targets include this file and any file contributing to the agenda - up to 2 levels deep
#+begin_src emacs-lisp
  (setq org-reverse-note-order t)
  (setq org-refile-targets (quote ((nil :maxlevel . 2)
                                   (org-agenda-files :maxlevel . 2))))
  (setq org-blank-before-new-entry nil)
#+end_src
*** Insert time slot
Insert time slot mainly used when I schedule meeting or appointment.

#+begin_src emacs-lisp
  (defvar current-hour-format "%H:00")

  (defun nc/insert-time-slot ()
    "Insert Time Slot"
    (interactive)
    (let ((begin (format-time-string current-hour-format (current-time)))
          (end (format-time-string current-hour-format (time-add (current-time) (seconds-to-time 3600)))))
      (insert (concat begin "-" end))))
#+end_src
*** My journal file

#+begin_src emacs-lisp
(defun nc/journal ()
  "Edit my journal"
  (interactive)
  (find-file-other-window (nc/expand-org-notes-path "GTD/journal.org")))

;; Binding journal file
(global-set-key "\C-cj" 'nc/journal)
#+end_src
*** Searching in my notes
#+begin_src emacs-lisp
(defun nc/helm-do-grep-notes ()
  "Search in all my org notes."
  (interactive)
  (helm-do-grep-1 (list nc/org-notes-directory) t nil (list "*.org")))
#+end_src

** Babel (Literate Programming)
*** Babel languages
#+begin_src emacs-lisp
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((sh . t)
       (python . t)))
#+end_src
*** Editing source code
 I don't want to get distracted by the same code in the other window, so I want org src to use the current window.

 #+begin_src emacs-lisp
   (setq org-src-window-setup 'current-window)
 #+end_src
*** Evaluate code blocks without prompting
#+begin_src emacs-lisp
  (setq org-confirm-babel-evaluate nil)
#+end_src
*** Syntax highlight in source blocks
#+begin_src emacs-lisp
  (setq org-src-fontify-natively t)
#+end_src
** Habits
#+begin_src emacs-lisp
(require 'org-habit)
(add-to-list 'org-modules "org-habit")
(setq org-habit-preceding-days 7
      org-habit-following-days 1
      org-habit-graph-column 80
      org-habit-show-habits-only-for-today t
      org-habit-show-all-today t)
#+end_src
** Org Crypt
#+begin_src emacs-lisp
  (require 'org-crypt)
  (org-crypt-use-before-save-magic)
  (setq org-tags-exclude-from-inheritance (quote ("crypt")))
  ;; GPG key to use for encryption
  ;; Either the Key ID or set to nil to use symmetric encryption.
  (setq org-crypt-key nil)
#+end_src
* Programming
** Expand region
    - expand selection with =C-==
    - contract with negative argument =M--= then =C-==
#+BEGIN_SRC emacs-lisp
(use-package expand-region
  :bind
  ("C-=" . er/expand-region))
#+END_SRC
** TODO Clojure
** Ediff
*** Ignore white space
From : [[https://www.emacswiki.org/emacs/EdiffMode]] :

You can ignore whitespace or case sensitivity in two ways:

 - Interactively, on the fly:
   - Whitespace sensitivity – Toggle with =##= (=ediff-toggle-skip-similar=).
   - Case sensitivity – Toggle with =#c= (=ediff-toggle-ignore-case=). This assumes that you’ve loaded library Lisp:ediff+.el and that you are using `diff(1)’ as ‘ediff-diff-program’. (Toggling case-sensitivity is available in vanilla GNU Emacs 22, so Lisp:ediff+.el is mainly useful for older Emacs versions.)
 - Persistently: Customize option =ediff-diff-options=. This assumes that you are using `diff(1)’ as ‘ediff-diff-program’.
    - Whitespace insensitivity – Include ‘-w’ in =ediff-diff-options=.
    - Case insensitivity – Include ‘-i’ in =ediff-diff-options=.
#+BEGIN_SRC emacs-lisp
(setq ediff-diff-options "-w")
#+END_SRC
*** Ediff operate on selected frame

Ediff should be opened in selected frame and split window horizontally

#+BEGIN_SRC emacs-lisp
(setq ediff-split-window-function 'split-window-horizontally)
(setq ediff-window-setup-function 'ediff-setup-windows-plain)
#+END_SRC
** Lua
#+BEGIN_SRC emacs-lisp
(use-package lua-mode
  :ensure t
  :mode "\\.lua\\'")
#+END_SRC
** Docker Files
#+begin_src emacs-lisp
  (use-package dockerfile-mode
    :mode "Dockerfile.*\\'")
#+end_src
** Magit
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :bind (("C-x g" . magit-status)))
#+END_SRC
** Markdown
#+BEGIN_SRC emacs-lisp
  (use-package markdown-mode
    :mode ("\\.\\(m\\(ark\\)?down\\|md\\)$" . markdown-mode)
    :config)
#+END_SRC
** Multiple Cursors

This package can create several cursors to all do the same things.

#+BEGIN_SRC emacs-lisp
  (use-package multiple-cursors
    :bind
    (("C-S-c C-S-c" .  mc/edit-lines)
     ("C-$" .  mc/edit-ends-of-lines)
     ("C-S-b" .  mc/edit-beginnings-of-lines)
     ("C-<" .  mc/mark-previous-word-like-this)
     ("C->" .  mc/mark-next-word-like-this)
     ("C-S-n" .  mc/mark-next-like-this)
     ("C-S-p" .  mc/mark-previous-like-this)
     ("C-*" .  mc/mark-all-dwim)))
#+END_SRC
** Smartparens

Smart parens for all modes.

#+BEGIN_SRC emacs-lisp
    (use-package smartparens
      :defer t
      :diminish ""
      :init
      (progn
        (add-hook 'prog-mode-hook #'turn-on-smartparens-mode)
        ;; turn on showing the match for clojure and elisp
        (add-hook 'clojure-mode-hook #'turn-on-show-smartparens-mode)
        (add-hook 'emacs-lisp-mode-hook #'turn-on-show-smartparens-mode)
        (add-hook 'java-mode-hook #'turn-on-show-smartparens-mode)
        (add-hook 'c-mode-hook #'turn-on-show-smartparens-mode))
      :config
      (setq-default sp-hybrid-kill-entire-symbol nil)

      (setq sp-highlight-pair-overlay nil)

      (define-key sp-keymap (kbd "<delete>") 'sp-delete-char)
      (define-key sp-keymap (kbd "C-<right>") 'sp-forward-slurp-sexp)
      (define-key sp-keymap (kbd "C-<left>") 'sp-forward-barf-sexp)
      (define-key sp-keymap (kbd "C-S-<right>") 'sp-backward-barf-sexp)
      (define-key sp-keymap (kbd "C-S-<left>") 'sp-backward-slurp-sexp)
      (define-key sp-keymap (kbd "M-s") 'sp-unwrap-sexp)
      (define-key sp-keymap (kbd "M-S-s") 'sp-raise-sexp)
      (define-key sp-keymap (kbd "M-i") 'sp-split-sexp)
      (define-key sp-keymap (kbd "M-S-i") 'sp-join-sexp)
      (define-key sp-keymap (kbd "M-t") 'sp-transpose-sexp)
      (define-key sp-keymap (kbd "M-S-<left>") 'sp-backward-sexp)
      (define-key sp-keymap (kbd "M-S-<right>") 'sp-forward-sexp)



      (defun sp--my-create-newline-and-enter-sexp (&rest _ignored)
        "Open a new brace or bracket expression, with relevant newlines and indent. "
        (newline)
        (indent-according-to-mode)
        (forward-line -1)
        (indent-according-to-mode))

      (sp-with-modes '(c-mode c++-mode js-mode js2-mode java-mode
                              typescript-mode perl-mode)
        (sp-local-pair "{" nil :post-handlers
                       '((sp--my-create-newline-and-enter-sexp "RET")))))
#+END_SRC

** Web
*** Rest Client
#+begin_src emacs-lisp
  (use-package restclient)
#+end_src
*** Web Mode
#+begin_src emacs-lisp
  (use-package web-mode
    :ensure t
    :config
    (add-to-list 'auto-mode-alist '("\\.html\\'" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.tag$" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.ftl$" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.jsp$" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.php$" . web-mode))
    (add-hook 'web-mode-hook (lambda ()
                               (setq web-mode-markup-indent-offset 4)
                               (setq web-mode-code-indent-offset 4))))
#+end_src
*** Javascript
#+begin_src emacs-lisp
  (use-package js2-mode
    :init
    (add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
    (defalias 'javascript-generic-mode 'js2-mode)
    :config
    (js2-imenu-extras-setup)
    (setq-default js-auto-indent-flag nil
                  js-indent-level 2)
    ;; Don't override global M-j keybinding (join lines)
    (define-key js2-mode-map (kbd "M-j") nil))
#+end_src

** Yasnippet

Snippets for programming.
#+BEGIN_SRC emacs-lisp
(use-package yasnippet
  :defer t
  :diminish yas-minor-mode
  :init (progn
          (yas-global-mode 1)
          (yas-reload-all)))
#+END_SRC

Allow with =M_== to choosing a snippet using helm (helm source for yasnippet)

#+BEGIN_SRC emacs-lisp
(use-package helm-c-yasnippet
  :ensure t
  :after yasnippet
  :init (bind-key "M-=" #'helm-yas-complete)
  :config (setq helm-yas-space-match-any-greedy t))
#+END_SRC

* Global keymap
** Duplicate line
Duplicate line with =C-c d=
#+BEGIN_SRC emacs-lisp
(defun nc/duplicate-current-line-or-region (arg)
  "Duplicates the current line or region ARG times.
If there's no region, the current line will be duplicated.  However, if
there's a region, all lines that region covers will be duplicated."
  (interactive "p")
  (let (beg end (origin (point)))
    (if (and mark-active (> (point) (mark)))
        (exchange-point-and-mark))
    (setq beg (line-beginning-position))
    (if mark-active
        (exchange-point-and-mark))
    (setq end (line-end-position))
    (let ((region (buffer-substring-no-properties beg end)))
      (-dotimes arg
                (lambda (n)
                  (goto-char end)
                  (newline)
                  (insert region)
                  (setq end (point))))
      (goto-char (+ origin (* (length region) arg) arg)))))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(bind-key "C-c d" 'nc/duplicate-current-line-or-region)
#+END_SRC

** Move Line
*** Move line Up
Move line Up is bound to =C-S-UpArrow=

#+BEGIN_SRC emacs-lisp
(defun nc/move-line-up ()
  "Move up the current line."
  (interactive)
  (transpose-lines 1)
  (forward-line -2)
  (indent-according-to-mode))

(global-set-key [(control shift up)]  'nc/move-line-up)
#+END_SRC
*** Move line down
Move line down is bound to =C-S-DownArrow=

#+BEGIN_SRC emacs-lisp
(defun move-line-down ()
  "Move down the current line."
  (interactive)
  (forward-line 1)
  (transpose-lines 1)
  (forward-line -1)
  (indent-according-to-mode))

(global-set-key [(control shift down)]  'move-line-down)
#+END_SRC

** Join lines
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "M-j") (lambda () (interactive) (join-line -1)))
#+END_SRC
** Increase or decrease text scale
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-+") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)
#+END_SRC
** Copy file name to clipboard
#+BEGIN_SRC emacs-lisp
(defun nc/copy-file-name-to-clipboard ()
  "Copy the current buffer file name to the clipboard."
  (interactive)
  (let ((filename (if (equal major-mode 'dired-mode)
                      default-directory
                    (buffer-file-name))))
    (when filename
      (kill-new filename)
      (message "Copied buffer file name '%s' to the clipboard." filename))))
#+END_SRC
** Kill
Prefer backward-kill-word over Backspace
https://sites.google.com/site/steveyegge2/effective-emacs

#+BEGIN_SRC emacs-lisp
(global-set-key "\C-w" 'backward-kill-word)
(global-set-key "\C-x\C-k" 'kill-region)
#+END_SRC
** Global keys for usefuls functions
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "<f2>") 'rgrep)
(global-set-key (kbd "C-<f2>") 'helm-do-ag)

(global-set-key (kbd "<f6>") 'magit-status)
(global-set-key (kbd "C-<f6>") 'magit-log-buffer-file)

;; Org mode keys
(global-set-key (kbd "<f12>") 'org-agenda)

(global-set-key (kbd "M-<f12>") 'shell)
(global-set-key (kbd "C-<f12>") 'helm-semantic-or-imenu)

#+END_SRC
** Goto line
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "M-g")         'goto-line)
#+END_SRC
** Windows
Move or create
*** Toggle window split
Bound to =C-c -=.
#+BEGIN_SRC emacs-lisp
  (defun nc/toggle-window-split ()
    (interactive)
    (if (= (count-windows) 2)
        (let* ((this-win-buffer (window-buffer))
               (next-win-buffer (window-buffer (next-window)))
               (this-win-edges (window-edges (selected-window)))
               (next-win-edges (window-edges (next-window)))
               (this-win-2nd (not (and (<= (car this-win-edges)
                                           (car next-win-edges))
                                       (<= (cadr this-win-edges)
                                           (cadr next-win-edges)))))
               (splitter
                (if (= (car this-win-edges)
                       (car (window-edges (next-window))))
                    'split-window-horizontally
                  'split-window-vertically)))
          (delete-other-windows)
          (let ((first-win (selected-window)))
            (funcall splitter)
            (if this-win-2nd (other-window 1))
            (set-window-buffer (selected-window) this-win-buffer)
            (set-window-buffer (next-window) next-win-buffer)
            (select-window first-win)
            (if this-win-2nd (other-window 1))))))

  (bind-key "C-c -" 'nc/toggle-window-split)
#+END_SRC
*** Split window right
Split window right with =C-c |= and move there
#+BEGIN_SRC emacs-lisp
(defun nc/split-window-right-and-move-there-dammit ()
  (interactive)
  (split-window-right)
  (windmove-right))

(bind-key "C-c |" 'nc/split-window-right-and-move-there-dammit)
#+END_SRC

*** Rotate windows
Rotate windows with =C-c r=
#+begin_src emacs-lisp :tangle yes
  (defun nc/rotate-windows ()
    "Rotate your windows"
    (interactive)
    (cond
     ((not (> (count-windows) 1)) (message "You can't rotate a single window!"))
     (t
      (let ((i 1)
            (num-windows (count-windows)))
        (while  (< i num-windows)
          (let* (
                 (w1 (elt (window-list) i))
                 (w2 (elt (window-list) (+ (% i num-windows) 1)))
                 (b1 (window-buffer w1))
                 (b2 (window-buffer w2))
                 (s1 (window-start w1))
                 (s2 (window-start w2))
                 )
            (set-window-buffer w1  b2)
            (set-window-buffer w2 b1)
            (set-window-start w1 s2)
            (set-window-start w2 s1)
            (setq i (1+ i))))))))

  (bind-key "C-c r" 'nc/rotate-windows)
#+end_src

** Registers
Used by key chord =JJ=
#+begin_src emacs-lisp
  (dolist (r `((?i (file . ,(concat user-emacs-directory "nchapon.org")))
               (?o (file . ,(nc/expand-org-notes-path "GTD/office.org")))
               (?r (file . ,(nc/expand-org-notes-path "GTD/refile.org")))
               (?t (file . ,(nc/expand-org-notes-path "GTD/todo.org")))
               (?w (file . ,(nc/expand-org-notes-path "GTD/watching.org")))))
    (set-register (car r) (cadr r)))
#+end_src
** Key Chords
#+BEGIN_SRC emacs-lisp
  (use-package key-chord
    :init
    (key-chord-mode 1)
    (key-chord-define-global "jj" 'ace-jump-word-mode)
    (key-chord-define-global "jl" 'ace-jump-line-mode)
    (key-chord-define-global "jk" 'ace-jump-char-mode)
    (key-chord-define-global "FF" 'projectile-find-file)
    (key-chord-define-global "GG" 'helm-projectile-ag)
    (key-chord-define-global "KK" 'kill-whole-line)
    (key-chord-define-global "JJ" 'jump-to-register)
    (key-chord-define-global "DD" 'delete-region)
    (key-chord-define-global "OO" 'helm-occur)
    (key-chord-define-global "??" 'nc/helm-do-grep-notes)
    (key-chord-define-global "BB" 'beginning-of-buffer)
    (key-chord-define-global "$$" 'end-of-buffer)
    (key-chord-define-global "xx" 'execute-extended-command)
    (key-chord-define-global "qq" 'nc/cleanup-buffer-or-region)
    (key-chord-define-global "yy" 'browse-kill-ring)
    )
#+END_SRC

* Notes
** Inspiration configs
https://writequit.org/org/settings.html
https://github.com/yveszoundi/emacs.d/blob/master/bootstrap/startup.org
