* Globals variables
** Personal Information
 #+BEGIN_SRC emacs-lisp
 (setq user-full-name "Nicolas Chapon"
         user-mail-address "nchapon@gmail.com")
 #+END_SRC

** Constants

#+BEGIN_SRC emacs-lisp
  (defconst is-mac (equal system-type 'darwin))
  (defconst is-linux (equal system-type 'gnu/linux))
  (defconst has-gui (display-graphic-p))
#+END_SRC

* Package configuration
** use-package
 #+BEGIN_SRC emacs-lisp
 (add-to-list 'package-archives
          '("melpa" . "http://melpa.org/packages/"))
 #+END_SRC

 Use package default configuration
  #+BEGIN_SRC emacs-lisp
    (unless (package-installed-p 'use-package)
        (package-refresh-contents)
        (package-install 'use-package))

    (setq use-package-verbose t)
    (setq use-package-always-ensure t)
    (require 'use-package)
    (use-package auto-compile
      :config (auto-compile-on-load-mode))

    (use-package diminish)
  #+END_SRC
** No Littering
#+BEGIN_QUOTE
Help keeping =~/.emacs.d= clean

[[https://github.com/emacscollective/no-littering][https://github.com/emacscollective/no-littering]]
#+END_QUOTE

#+begin_src emacs-lisp
(use-package no-littering)
#+end_src
** Customization
To avoid overloading the GNU Emacs custormization =init.el= file made by the
user with the UI, I add the generated code in a separate file.

#+BEGIN_SRC emacs-lisp
  (setq-default custom-file (expand-file-name "custom.el" user-emacs-directory))
  (when (file-exists-p custom-file)
    (load custom-file t))
#+END_SRC

** Exec Path From Shell

#+BEGIN_QUOTE
A GNU Emacs library to ensure environment variables inside Emacs look the same as in the user's shell.
This happens a lot on OS X, where an Emacs instance started from the GUI inherits a default set of environment variables.

[[https://github.com/purcell/exec-path-from-shell][https://github.com/purcell/exec-path-from-shell]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
  (use-package exec-path-from-shell
    :config
    (when (memq window-system '(mac ns x))
      (progn
        (exec-path-from-shell-initialize)
        (exec-path-from-shell-copy-env "GOPATH")
        (exec-path-from-shell-copy-env "RUST_SRC_PATH"))))
#+END_SRC
* UI
** All The Icons
#+BEGIN_SRC emacs-lisp
(use-package all-the-icons)
#+END_SRC
** Theme
Using moe theme dark all the day
#+BEGIN_SRC emacs-lisp
  (use-package doom-themes

    :config

    ;; Global settings (defaults)
    (setq doom-themes-enable-bold t    ; if nil, bold is universally disabled
          doom-themes-enable-italic t) ; if nil, italics is universally disabled

    ;; Load the theme (doom-one, doom-molokai, etc); keep in mind that each theme
    ;; may have their own settings.
    (load-theme 'doom-one t)

    ;; Enable flashing mode-line on errors
    (doom-themes-visual-bell-config)

    (doom-themes-org-config)

    ;; Enable custom neotree theme (all-the-icons must be installed!)
    ;;(doom-themes-neotree-config)
    ;; or for treemacs users
    ;;(doom-themes-treemacs-config)

    ;; Corrects (and improves) org-mode's native fontification.
    (doom-themes-org-config))
#+END_SRC
** Mode line
#+BEGIN_SRC emacs-lisp
  (use-package doom-modeline
    :hook (after-init . doom-modeline-init))
#+END_SRC

** Font
Use Input Font (http://input.fontbureau.com/)  on Linux, Monaco on MacOS

#+BEGIN_SRC emacs-lisp
  (defun nc/setup-font ()
    "Set up font height"
    (interactive)
    (when is-linux
      (set-frame-font "Input Mono-12" nil t))
    (when is-mac
      (set-frame-font "Monaco 15" nil t)))

  (when has-gui
    (add-hook 'after-init-hook #'nc/setup-font))
#+END_SRC

** Windows configuration
*** No menu and toolbar

#+BEGIN_SRC emacs-lisp
(if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
(if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
(if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
#+END_SRC

*** No welcome screen

#+BEGIN_SRC emacs-lisp
(setq  inhibit-startup-message t)
#+END_SRC

** Make fringe smaller

#+BEGIN_SRC emacs-lisp
  (if (fboundp 'fringe-mode)
      (fringe-mode 2))
#+END_SRC
* General Settings
** Better defaults
*** Miscellaneous
 #+BEGIN_SRC emacs-lisp
 (setq initial-major-mode 'lisp-interaction-mode
       redisplay-dont-pause t
       column-number-mode t
       echo-keystrokes 0.02
       transient-mark-mode t
       shift-select-mode nil
       require-final-newline t
       truncate-partial-width-windows nil
       delete-by-moving-to-trash t
       confirm-nonexistent-file-or-buffer nil
       query-replace-highlight t)
 #+END_SRC
*** Indentation & Tabs
**** Default indentation
 Always spaces with width of 4
 #+BEGIN_SRC emacs-lisp
 (setq-default indent-tabs-mode nil)
 (setq-default tab-width 4)
 #+END_SRC
**** Indent new line if necessary
 #+BEGIN_SRC emacs-lisp
 (define-key global-map (kbd "RET") 'newline-and-indent)
 #+END_SRC
*** Transparently open compressed files

 #+BEGIN_SRC emacs-lisp
 (auto-compression-mode t)
 #+END_SRC

*** Always display line and column numbers
 #+BEGIN_SRC emacs-lisp
 (setq line-number-mode t)
 (setq column-number-mode t)
 #+END_SRC
*** Answering just 'y' or 'n'

 #+BEGIN_SRC emacs-lisp
 (defalias 'yes-or-no-p 'y-or-n-p)
 #+END_SRC

*** Increase or decrease text scale
 #+BEGIN_SRC emacs-lisp
 (global-set-key (kbd "C-+") 'text-scale-increase)
 (global-set-key (kbd "C--") 'text-scale-decrease)
 #+END_SRC
*** Lines should be 80 characters
 #+BEGIN_SRC emacs-lisp
 (setq fill-column 80)
 #+END_SRC
*** Disable annoying audio notifications
 #+BEGIN_SRC emacs-lisp
 (setq ring-bell-function 'ignore)
 #+END_SRC
*** Ediff
**** Ignore white space
 From : [[https://www.emacswiki.org/emacs/EdiffMode]] :

 You can ignore whitespace or case sensitivity in two ways:

  - Interactively, on the fly:
    - Whitespace sensitivity – Toggle with =##= (=ediff-toggle-skip-similar=).
    - Case sensitivity – Toggle with =#c= (=ediff-toggle-ignore-case=). This assumes that you’ve loaded library Lisp:ediff+.el and that you are using `diff(1)’ as ‘ediff-diff-program’. (Toggling case-sensitivity is available in vanilla GNU Emacs 22, so Lisp:ediff+.el is mainly useful for older Emacs versions.)
  - Persistently: Customize option =ediff-diff-options=. This assumes that you are using `diff(1)’ as ‘ediff-diff-program’.
     - Whitespace insensitivity – Include ‘-w’ in =ediff-diff-options=.
     - Case insensitivity – Include ‘-i’ in =ediff-diff-options=.
 #+BEGIN_SRC emacs-lisp
 (setq ediff-diff-options "-w")
 #+END_SRC
**** Ediff operate on selected frame

 Ediff should be opened in selected frame and split window horizontally

 #+BEGIN_SRC emacs-lisp
 (setq ediff-split-window-function 'split-window-horizontally)
 (setq ediff-window-setup-function 'ediff-setup-windows-plain)
 #+END_SRC
*** UTF-8
 Set all coding systems to utf-8
 #+BEGIN_SRC emacs-lisp
 (prefer-coding-system 'utf-8-unix)
 (set-clipboard-coding-system 'utf-8-unix)
 (set-default-coding-systems 'utf-8-unix)
 (set-keyboard-coding-system 'utf-8-unix)
 (set-language-environment 'utf-8)
 (set-selection-coding-system 'utf-8-unix)
 (set-terminal-coding-system 'utf-8-unix)
 (setq locale-coding-system 'utf-8-unix)
 (setq coding-system-for-write 'utf-8-unix)
 (setq default-buffer-file-coding-system 'utf-8-unix)
 (setq default-process-coding-system '(utf-8-unix . utf-8-unix))
 (setq file-name-coding-system  'utf-8)
 #+END_SRC
*** Calendar
**** French Calendar
 #+BEGIN_SRC emacs-lisp
   (setq calendar-week-start-day 1
         calendar-day-name-array ["Dimanche" "Lundi" "Mardi" "Mercredi"
                                  "Jeudi" "Vendredi" "Samedi"]
         calendar-month-name-array ["Janvier" "Fevrier" "Mars" "Avril" "Mai"
                                    "Juin" "Juillet" "Aout" "Septembre"
                                    "Octobre" "Novembre" "Decembre"])
 #+END_SRC
**** French holiday
 #+BEGIN_SRC emacs-lisp
   (defvar french-holiday
     '((holiday-fixed 1 1 "Jour de l'an")
       (holiday-fixed 5 1 "Fête du travail")
       (holiday-fixed 5 8 "Victoire 45")
       (holiday-fixed 7 14 "Fête nationale")
       (holiday-fixed 8 15 "Assomption")
       (holiday-fixed 11 1 "Toussaint")
       (holiday-fixed 11 11 "Armistice 18")
       (holiday-fixed 12 25 "Noël")
       (holiday-easter-etc 1 "Lundi de Pâques")
       (holiday-easter-etc 39 "Ascension")
       (holiday-easter-etc 50 "Lundi de Pentecôte")))

   (setq calendar-date-style 'european
         calendar-holidays french-holiday
         calendar-mark-holidays-flag t
         calendar-mark-diary-entries-flag t)

 #+END_SRC
** Completion
*** Company
 =company= provides auto completion mode.
 #+BEGIN_SRC emacs-lisp
   (use-package company
     :defer t
     :diminish ""
     :bind (("M-/" . company-complete)
            ("C-c C-y" . company-yasnippet)
            :map company-active-map
            ("C-p" . company-select-previous)
            ("C-n" . company-select-next)
            ("TAB" . company-complete-common-or-cycle)
            ("<tab>" . company-complete-common-or-cycle)
            ("C-d" . company-show-doc-buffer))
     :init (global-company-mode)
     :config
     (progn
       (setq company-idle-delay 0.1
             ;; min prefix of 1 chars
             company-minimum-prefix-length 2
             company-selection-wrap-around t
             company-show-numbers t
             company-dabbrev-downcase nil
             company-dabbrev-code-everywhere t
             company-transformers '(company-sort-by-occurrence))))

 #+END_SRC
*** Helm
**** Helm core configuration
 #+BEGIN_SRC emacs-lisp
   (use-package helm
     :diminish helm-mode

     :config (setq helm-idle-delay 0.0 ; update fast sources immediately (doesn't).
                   helm-input-idle-delay 0.01  ; this actually updates things
                                           ; reeeelatively quickly.
                   helm-yas-display-key-on-candidate t
                   helm-quick-update t
                   helm-split-window-in-side-p t
                   helm-buffers-fuzzy-matching t
                   helm-move-to-line-cycle-in-source t
                   helm-ff-search-library-in-sexp t
                   helm-ff-file-name-history-use-recentf t
                   helm-M-x-requires-pattern nil
                   helm-ff-skip-boring-files t
                   helm-for-files-preferred-list (quote (helm-source-files-in-current-dir helm-source-recentf helm-source-bookmarks helm-source-file-cache helm-source-buffers-list helm-source-locate helm-source-ls-git)))

     :init (progn
             (require 'helm-config)
             (helm-mode t)

             (use-package helm-projectile)
             (helm-projectile-on))

     :bind (("C-x b" . helm-mini)
            ("M-x" . helm-M-x)
            ("C-x C-f" . helm-find-files)
            ("C-h f" . helm-apropos)
            ("C-x C-b" . helm-buffers-list)
            ("M-y" . helm-show-kill-ring)
            ("C-x c o" . helm-occur)
            ("C-x C-r" . helm-recentf)
            ("C-x c y" . helm-yas-complete)
            ("C-x c Y" . helm-yas-create-snippet-on-region)
            ("C-x c SPC" . helm-all-mark-rings)))
 #+END_SRC
**** helm-swoop
     - From https://github.com/malb/emacs.d/blob/master/malb.org#helm-swoop
     - Tip :: You can edit helm-swoop buffers by pressing =C-c C-e=.

 #+begin_src emacs-lisp
   (use-package helm-swoop
     :ensure t
     :bind (("C-c o s" . helm-multi-swoop-org)
            ("C-s"   . nc/swoop-or-search)
            ("C-M-s" . helm-multi-swoop-all))
     :config (progn
               (setq nc/helm-swoop-ignore-major-mode
                     '(dired-mode
                       paradox-menu-mode
                       doc-view-mode
                       pdf-view-mode
                       mu4e-headers-mode
                       latex-mode))

               (setq helm-swoop-pre-input-function  #'nc--helm-swoop-pre-fill
                     helm-swoop-split-with-multiple-windows nil
                     helm-swoop-split-direction #'split-window-horizontally
                     helm-swoop-split-window-function 'helm-default-display-buffer
                     helm-swoop-speed-or-color t)

               (defun nc--helm-swoop-pre-fill ()
                 (thing-at-point 'symbol))

               ;; https://emacs.stackexchange.com/questions/28790/helm-swoop-how-to-make-it-behave-more-like-isearch
               (defun nc/helm-swoop-C-s ()
                 (interactive)
                 (if (boundp 'helm-swoop-pattern)
                     (if (equal helm-swoop-pattern "")
                         (previous-history-element 1)
                       (helm-next-line))
                   (helm-next-line)))

               (defun nc/swoop-or-search ()
                 (interactive)
                 (if (or (> (buffer-size) 1048576) ;; helm-swoop can be slow on big buffers
                         (memq major-mode nc/helm-swoop-ignore-major-mode))
                     (isearch-forward)
                   (helm-swoop)))

               (bind-key "C-S-s" #'helm-swoop-from-isearch isearch-mode-map)
               (bind-key "C-S-s" #'helm-multi-swoop-all-from-helm-swoop helm-swoop-map)
               (bind-key "C-r"   #'helm-previous-line helm-swoop-map)
               (bind-key "C-s"   #'nc/helm-swoop-C-s helm-swoop-map)
               (bind-key "C-r"   #'helm-previous-line helm-multi-swoop-map)
               (bind-key "C-s"   #'nc/helm-swoop-C-s helm-multi-swoop-map)))
 #+end_src
**** helm-ag
 Can integrate Helm with [[https://github.com/ggreer/the_silver_searcher][The Silver Searcher]] (ag A code searching tool similar to ack, with a focus on speed.)

 #+BEGIN_SRC emacs-lisp
 (use-package helm-ag)

 (global-set-key (kbd "C-<f2>") 'helm-do-ag)
 #+END_SRC
**** helm-tramp
 Display server list from your =~/.ssh/config= with helm interface
 #+begin_src emacs-lisp
   (use-package helm-tramp)
 #+end_src

 Set tramp default method to ssh

 #+begin_src emacs-lisp
 (setq tramp-default-method "ssh")
 #+end_src
**** helm-org-rifle
 Search in org headings / content like Google
 #+BEGIN_SRC emacs-lisp
   (use-package helm-org-rifle
     :ensure t
     :defer t
     :config (progn
               (defun nc/helm-org-rifle-agenda-files (arg)
                 (interactive "p")
                 (let ((current-prefix-arg nil))
                   (cond
                    ((equal arg 4) (call-interactively #'helm-org-rifle-agenda-files nil))
                    ((equal arg 16) (helm-org-rifle-occur-agenda-files))
                    (t (helm-org-agenda-files-headings)))))))
 #+END_SRC
**** helm-semantic and imenu
     - From https://github.com/malb/emacs.d/blob/master/malb.org#helm-semantic-imenu-org
 #+begin_src emacs-lisp
   (defun nc/helm-in-buffer ()
     "the right kind of buffer menu"
     (interactive)
     (if (eq major-mode 'org-mode)
         (call-interactively #'helm-org-in-buffer-headings)
       (call-interactively #'helm-semantic-or-imenu)))

   (global-set-key (kbd "C-<f12>") 'nc/helm-in-buffer)
 #+end_src
*** Hippie expand
 Looks at the word before point and tries  to expand it.

 #+BEGIN_SRC emacs-lisp
 (setq hippie-expand-try-functions-list
   '(try-complete-file-name-partially
     try-complete-file-name
     try-expand-all-abbrevs
     try-expand-dabbrev
     try-expand-dabbrev-visible
     try-expand-dabbrev-all-buffers
     try-expand-dabbrev-from-kill
     try-complete-lisp-symbol-partially
     try-complete-lisp-symbol))
 #+END_SRC

 #+BEGIN_SRC emacs-lisp
 (bind-key "M-/" 'hippie-expand)
 #+END_SRC

*** Yasnippet
 Snippets for programming.

 #+BEGIN_SRC emacs-lisp
   (use-package yasnippet
     :ensure t
     :diminish yas-minor-mode
     :config
     (yas-global-mode 1)
     (yas-reload-all))
 #+END_SRC

 Allow =M-== to choosing a snippet using helm (helm source for yasnippet)

 #+BEGIN_SRC emacs-lisp
 (use-package helm-c-yasnippet
   :ensure t
   :after yasnippet
   :init (bind-key "M-=" #'helm-yas-complete)
   :config (setq helm-yas-space-match-any-greedy t))
 #+END_SRC

** Buffers
*** Auto revert mode
Revert buffers automatically when underlying files are changed externally.
#+BEGIN_SRC emacs-lisp
  (global-auto-revert-mode 1)
  (setq global-auto-revert-non-file-buffers t
        auto-revert-verbose nil)
#+END_SRC

*** Uniquify
Use file path to ensure buffer name uniqueness

#+BEGIN_SRC emacs-lisp
(require 'uniquify)
(setq uniquify-buffer-name-style 'forward)
(setq uniquify-separator "/")
(setq uniquify-after-kill-buffer-p t)
(setq uniquify-ignore-buffers-re "^\\*")
#+END_SRC
** Dired
*** Always delete and copy recursively
#+BEGIN_SRC emacs-lisp
(setq dired-recursive-deletes 'always)
(setq dired-recursive-copies 'always)
#+END_SRC
*** Human readable size

#+begin_src emacs-lisp
  (setq dired-listing-switches "-alh")
#+end_src

To sort by file size change sort value we can use =C-u s=

*** Dired-x
Enable C-x C-j
#+BEGIN_SRC emacs-lisp
(require 'dired-x)
#+END_SRC
*** dwim target copy

#+begin_src emacs-lisp
  (setq dired-dwim-target t)
#+end_src
*** Font Lock Dired
#+BEGIN_SRC emacs-lisp
  (use-package diredfl
    :init (diredfl-global-mode 1))
#+END_SRC
*** All the icons
#+BEGIN_SRC emacs-lisp
(use-package all-the-icons-dired
  :ensure t
  :diminish all-the-icons-dired-mode
  :init
  (add-hook 'dired-mode-hook 'all-the-icons-dired-mode))
#+END_SRC
** Editing
*** Duplicate line
 Duplicate line with =C-c d=
 #+BEGIN_SRC emacs-lisp
 (defun nc/duplicate-current-line-or-region (arg)
   "Duplicates the current line or region ARG times.
 If there's no region, the current line will be duplicated.  However, if
 there's a region, all lines that region covers will be duplicated."
   (interactive "p")
   (let (beg end (origin (point)))
     (if (and mark-active (> (point) (mark)))
         (exchange-point-and-mark))
     (setq beg (line-beginning-position))
     (if mark-active
         (exchange-point-and-mark))
     (setq end (line-end-position))
     (let ((region (buffer-substring-no-properties beg end)))
       (-dotimes arg
                 (lambda (n)
                   (goto-char end)
                   (newline)
                   (insert region)
                   (setq end (point))))
       (goto-char (+ origin (* (length region) arg) arg)))))
 #+END_SRC

 #+BEGIN_SRC emacs-lisp
 (bind-key "C-c d" 'nc/duplicate-current-line-or-region)
 #+END_SRC

*** Expand region
     - expand selection with =C-==
     - contract with negative argument =M--= then =C-==

 #+BEGIN_QUOTE
 Expand region increases the selected region by semantic units. Just keep pressing the key until it selects what you want.

 [[https://github.com/magnars/expand-region.el]]
 #+END_QUOTE

 #+BEGIN_SRC emacs-lisp
 (use-package expand-region
   :bind
   ("C-=" . er/expand-region))
 #+END_SRC
*** Join lines
 #+BEGIN_SRC emacs-lisp
 (global-set-key (kbd "M-j") (lambda () (interactive) (join-line -1)))
 #+END_SRC
*** Kill
 Prefer backward-kill-word over Backspace
 https://sites.google.com/site/steveyegge2/effective-emacs

 #+BEGIN_SRC emacs-lisp
 (global-set-key "\C-w" 'backward-kill-word)
 (global-set-key "\C-x\C-k" 'kill-region)
 #+END_SRC
**** Kill whole line
 Kill whole line with
 #+BEGIN_SRC emacs-lisp
 (global-set-key (kbd "S-<backspace>") 'kill-whole-line)
 #+END_SRC

*** Multiple Cursors

 This package can create several cursors to all do the same things.

 #+BEGIN_SRC emacs-lisp
   (use-package multiple-cursors
     :bind
     (("C-S-c C-S-c" .  mc/edit-lines)
      ("C-$" .  mc/edit-ends-of-lines)
      ("C-S-b" .  mc/edit-beginnings-of-lines)
      ("C-<" .  mc/mark-previous-word-like-this)
      ("C->" .  mc/mark-next-word-like-this)
      ("C-S-n" .  mc/mark-next-like-this)
      ("C-S-p" .  mc/mark-previous-like-this)
      ("C-*" .  mc/mark-all-dwim)))
 #+END_SRC
*** Move Line
**** Move line Up
 Move line Up is bound to =C-S-UpArrow=

 #+BEGIN_SRC emacs-lisp
 (defun nc/move-line-up ()
   "Move up the current line."
   (interactive)
   (transpose-lines 1)
   (forward-line -2)
   (indent-according-to-mode))

 (global-set-key [(control shift up)]  'nc/move-line-up)
 #+END_SRC
**** Move line down
 Move line down is bound to =C-S-DownArrow=

 #+BEGIN_SRC emacs-lisp
 (defun nc/move-line-down ()
   "Move down the current line."
   (interactive)
   (forward-line 1)
   (transpose-lines 1)
   (forward-line -1)
   (indent-according-to-mode))

 (global-set-key [(control shift down)]  'nc/move-line-down)
 #+END_SRC
*** Super Save
Auto save buffers when buffers loose focus, disabled for remote buffers.
#+BEGIN_SRC emacs-lisp
  (use-package super-save
    :ensure t
    :config
    (setq super-save-auto-save-when-idle t
          super-save-remote-files nil)
    (add-to-list 'super-save-triggers 'ace-window)
    (super-save-mode +1))
#+END_SRC

*** Undo Tree
 This lets you use =C-x u= (=undo-tree-visualize=)
 #+BEGIN_SRC emacs-lisp
 (use-package undo-tree
   :diminish undo-tree-mode
   :config
   (progn
     (global-undo-tree-mode)
     (setq undo-tree-visualizer-timestamps t)
     (setq undo-tree-visualizer-diff t)))
 #+END_SRC

** Files
*** Core commands
    #+BEGIN_SRC emacs-lisp
      (bind-key "<f5>" 'revert-buffer)
      (bind-key "C-c f l" 'find-file-literally)
    #+END_SRC
*** Recent Files

 #+BEGIN_QUOTE
 Recentf is a minor mode that builds a list of recently opened
 files. This list is is automatically saved across sessions on exiting
 Emacs - you can then access this list through a command or the menu.

 [[https://www.emacswiki.org/emacs/RecentFiles][https://www.emacswiki.org/emacs/RecentFiles]]
 #+END_QUOTE

 #+BEGIN_SRC emacs-lisp
   (use-package recentf
     :config
     (setq recentf-max-menu-items 15
           recentf-max-saved-items 200))
 #+END_SRC

*** Backup files
 #+BEGIN_SRC emacs-lisp
 (setq delete-old-versions t  ; delete excess backup versions silently
     version-control t        ; numbered versions
)
 #+END_SRC
*** Copy file name to clipboard
 #+BEGIN_SRC emacs-lisp
    (defun nc/copy-filename-to-clipboard ()
      "Copy the current buffer file name to the clipboard."
      (interactive)
      (let ((filename (if (equal major-mode 'dired-mode)
                          default-directory
                        (buffer-file-name))))
        (when filename
          (kill-new filename)
          (message "Copied buffer file name '%s' to the clipboard." filename))))

   (bind-key "C-c f w" #'nc/copy-filename-to-clipboard)
 #+END_SRC

*** Delete file
#+BEGIN_SRC emacs-lisp
  (defun nc/delete-this-file ()
    "Kill the current buffer and deletes the file it is visiting."
    (interactive)
    (let ((filename (buffer-file-name)))
      (when filename
        (if (vc-backend filename)
            (vc-delete-file filename)
          (when (y-or-n-p (format "Are you sure you want to delete %s? " filename))
            (delete-file filename)
            (message "Deleted file %s" filename)
            (kill-buffer))))))

  (bind-key "C-c f D" #'nc/delete-this-file)
#+END_SRC
*** Rename file
#+BEGIN_SRC emacs-lisp
  (defun nc/rename-this-file-and-buffer ()
    "Renames current buffer and file it is visiting."
    (interactive)
    (let ((filename (buffer-file-name)))
      (if (not (and filename (file-exists-p filename)))
          (message "Buffer is not visiting a file!")
        (let ((new-name (read-file-name "New name: " filename)))
          (cond
           ((vc-backend filename) (vc-rename-file filename new-name))
           (t
            (rename-file filename new-name t)
            (set-visited-file-name new-name t t)))))))

  (bind-key "C-c f R" #'nc/rename-this-file-and-buffer)
#+END_SRC

*** Emacs Config File

 #+begin_src emacs-lisp
   (defun nc/find-config ()
       "Edit nchapon.org"
       (interactive)
       (find-file "~/.emacs.d/nchapon.org"))

     (global-set-key (kbd "C-c f I") 'nc/find-config)
 #+end_src

** Key Bindings
*** Which Key

 #+BEGIN_QUOTE
 =which-key= is a minor mode for Emacs that displays the key bindings following your currently entered incomplete command (a prefix) in a popup.

 [[https://github.com/justbur/emacs-which-key][Justin Burkett]]
 #+END_QUOTE

 #+BEGIN_SRC emacs-lisp
 (use-package which-key
     :config
     (which-key-mode))
 #+END_SRC

*** Key Chords
 #+BEGIN_SRC emacs-lisp
   (use-package key-chord
     :init
     (key-chord-mode 1)
     (key-chord-define-global "jj" 'ace-jump-word-mode)
     (key-chord-define-global "jl" 'ace-jump-line-mode)
     (key-chord-define-global "jk" 'ace-jump-char-mode)
     (key-chord-define-global "FF" 'projectile-find-file)
     (key-chord-define-global "GG" 'helm-projectile-ag)
     (key-chord-define-global ";h" 'helm-org-rifle)
     (key-chord-define-global "HH" 'nc/helm-org-rifle-agenda-files)
     (key-chord-define-global "DD" 'delete-region)
     (key-chord-define-global "OO" 'helm-occur)
     (key-chord-define-global "??" 'nc/helm-do-grep-notes)
     (key-chord-define-global "BB" 'beginning-of-buffer)
     (key-chord-define-global "WW" 'nc/swap-windows)
     (key-chord-define-global "$$" 'end-of-buffer)
     (key-chord-define-global "kk" 'kill-this-buffer))
 #+END_SRC
*** Hydra
#+BEGIN_SRC emacs-lisp
  (use-package hydra :ensure t)
#+END_SRC
*** Globals Keys
**** Rgrep
 #+BEGIN_SRC emacs-lisp
   (bind-key "<f2>" 'rgrep)
 #+END_SRC
**** Undo
#+BEGIN_SRC emacs-lisp
(bind-key "C-z" #'undo)
#+END_SRC
** Mac OS Specific Settings
*** Dired options

 #+BEGIN_SRC emacs-lisp
    ;; brew install coreutils
   (if (executable-find "gls")
       (progn
         (setq insert-directory-program "gls")
         (setq dired-listing-switches "-lFaGh1v --group-directories-first"))
     (setq dired-listing-switches "-ahlF"))
 #+END_SRC

*** Keys for apple keyboard
 #+BEGIN_SRC emacs-lisp
   (when is-mac
     (setq mac-command-modifier 'meta)    ; make cmd key do Meta
     (setq mac-option-modifier 'super)    ; make opt key do Super
     (setq mac-control-modifier 'control) ; make Control key do Control
     (setq ns-function-modifier 'hyper)   ; make Fn key do Hyper
   )
 #+END_SRC
*** Mac right option
 This will allow you to use the right ~⌥~ key to write symbols ={[]}=. The left ~⌥~ key can be used as the Meta
 key.
 #+BEGIN_SRC emacs-lisp
   (when is-mac
     (setq-default mac-right-option-modifier nil))
 #+END_SRC
*** GPG
 #+BEGIN_SRC emacs-lisp
   (when is-mac
     (setf epa-pinentry-mode 'loopback))
 #+END_SRC
*** French Locale
 #+BEGIN_SRC emacs-lisp
   (when is-mac
     (set-locale-environment "fr_FR.UTF-8"))
 #+END_SRC
** Navigation
*** Basic navigation
#+BEGIN_SRC emacs-lisp
  (bind-key "s-<up>" 'beginning-of-buffer) ;; first line
  (bind-key "s-<down>" 'end-of-buffer)     ;; last line
#+END_SRC
*** ace-jump
 #+BEGIN_SRC emacs-lisp
   (use-package ace-jump-mode
     :bind
     (("C-c /" . ace-jump-mode)
      ("C-c k". ace-jump-mode-pop-mark)))
 #+END_SRC
*** Goto line
 #+BEGIN_SRC emacs-lisp
 (global-set-key (kbd "M-g")         'goto-line)
 #+END_SRC
*** Move to beginning of line
 From  [[https://github.com/bbatsov/prelude]]
 See article [[http://emacsredux.com/blog/2013/05/22/smarter-navigation-to-the-beginning-of-a-line/]]
 #+BEGIN_SRC emacs-lisp
 (defun nc/smarter-move-beginning-of-line (arg)
   "Move point back to indentation of beginning of line.

 Move point to the first non-whitespace character on this line.
 If point is already there, move to the beginning of the line.
 Effectively toggle between the first non-whitespace character and
 the beginning of the line.

 If ARG is not nil or 1, move forward ARG - 1 lines first.  If
 point reaches the beginning or end of the buffer, stop there."
   (interactive "^p")
   (setq arg (or arg 1))

   ;; Move lines first
   (when (/= arg 1)
     (let ((line-move-visual nil))
       (forward-line (1- arg))))

   (let ((orig-point (point)))
     (back-to-indentation)
     (when (= orig-point (point))
       (move-beginning-of-line 1))))

 (global-set-key [remap move-beginning-of-line]
                 'nc/smarter-move-beginning-of-line)

 #+END_SRC
** Projectile
#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :diminish projectile-mode

    :init
    (setq projectile-enable-caching t)
    ;; Custom mode line
    (setq projectile-mode-line '(:eval (format " Ⓟ[%s]" (projectile-project-name))))
    :bind-keymap ("C-c p" . projectile-command-map)
    :config
    ;;(setq projectile-keymap-prefix (kbd "C-c p"))
    (add-to-list 'projectile-globally-ignored-directories "elpa")
    (add-to-list 'projectile-globally-ignored-directories "target")
    (add-to-list 'projectile-globally-ignored-directories ".cache")
    (add-to-list 'projectile-globally-ignored-directories "image-dired")
    (add-to-list 'projectile-globally-ignored-files "node_modules")
    (projectile-global-mode))
#+END_SRC

** Windows
*** ace-window
Perhaps I need to use =switch-window= (Cf  https://github.com/dimitri/switch-window)
 #+BEGIN_SRC emacs-lisp
   (use-package ace-window
     :bind (([remap other-window] . ace-window))
     :config
     (setq aw-keys '(?q ?s ?d ?f ?g ?h ?j ?k ?l))
     ;; increase size face
     (custom-set-faces
      '(aw-leading-char-face
        ((t (:inherit ace-jump-face-foreground :height 3.0))))))
 #+END_SRC
*** golden-ratio
 Resize automatically the windows you are working

 #+BEGIN_SRC emacs-lisp
   (use-package golden-ratio
     :ensure t
     :diminish t
     :init
     (golden-ratio-mode 1)
     :config
     (setq golden-ratio-extra-commands
           (append golden-ratio-extra-commands
                   '(ace-window))))
 #+END_SRC

*** Toggle window split
Bound to =C-c -=.
#+BEGIN_SRC emacs-lisp
  (defun nc/toggle-window-split ()
    (interactive)
    (if (= (count-windows) 2)
        (let* ((this-win-buffer (window-buffer))
               (next-win-buffer (window-buffer (next-window)))
               (this-win-edges (window-edges (selected-window)))
               (next-win-edges (window-edges (next-window)))
               (this-win-2nd (not (and (<= (car this-win-edges)
                                           (car next-win-edges))
                                       (<= (cadr this-win-edges)
                                           (cadr next-win-edges)))))
               (splitter
                (if (= (car this-win-edges)
                       (car (window-edges (next-window))))
                    'split-window-horizontally
                  'split-window-vertically)))
          (delete-other-windows)
          (let ((first-win (selected-window)))
            (funcall splitter)
            (if this-win-2nd (other-window 1))
            (set-window-buffer (selected-window) this-win-buffer)
            (set-window-buffer (next-window) next-win-buffer)
            (select-window first-win)
            (if this-win-2nd (other-window 1))))))

  (bind-key "C-c -" 'nc/toggle-window-split)
#+END_SRC
*** Split window right
Split window right with =C-c |= and move there
#+BEGIN_SRC emacs-lisp
(defun nc/split-window-right-and-move-there-dammit ()
  (interactive)
  (split-window-right)
  (windmove-right))

(bind-key "C-c |" 'nc/split-window-right-and-move-there-dammit)
#+END_SRC

*** Rotate windows
Rotate windows with =C-c r=
#+begin_src emacs-lisp
  (defun nc/rotate-windows ()
    "Rotate your windows"
    (interactive)
    (cond
     ((not (> (count-windows) 1)) (message "You can't rotate a single window!"))
     (t
      (let ((i 1)
            (num-windows (count-windows)))
        (while  (< i num-windows)
          (let* (
                 (w1 (elt (window-list) i))
                 (w2 (elt (window-list) (+ (% i num-windows) 1)))
                 (b1 (window-buffer w1))
                 (b2 (window-buffer w2))
                 (s1 (window-start w1))
                 (s2 (window-start w2))
                 )
            (set-window-buffer w1  b2)
            (set-window-buffer w2 b1)
            (set-window-start w1 s2)
            (set-window-start w2 s1)
            (setq i (1+ i))))))))

  (bind-key "C-c r" 'nc/rotate-windows)
#+end_src
*** Swap windows
    From https://github.com/zamansky/using-emacs/blob/master/myinit.org
#+begin_src emacs-lisp
  (defun nc/swap-windows ()
    "Swap windows"
    (interactive)
    (ace-swap-window)
    (aw-flip-window))
#+end_src
** Hooks
*** Cleanup before save
 Remove all trailing whitespace and trailing blank lines before saving the file
 #+BEGIN_SRC emacs-lisp
 (add-hook 'before-save-hook 'whitespace-cleanup)
 #+END_SRC
*** Copying lines without selecting them
    From http://emacs-fu.blogspot.fr/2009/11/copying-lines-without-selecting-them.html
     - =M-w= will copy current line without selection

 #+begin_src emacs-lisp
   (defadvice kill-ring-save (before slick-copy activate compile)
     "When called  interactively with no active region, copy a single line instead."
     (interactive
      (if mark-active (list (region-beginning) (region-end))
        (message "Copied line") (list (line-beginning-position) (line-beginning-position 2)))))

 #+end_src

*** Emacs Server

  #+BEGIN_SRC emacs-lisp
    (server-start)

    (add-hook 'after-make-frame-functions
              (lambda (frame)
                (select-frame frame)
                (nc/setup-font)))
  #+END_SRC

* Org
** Global preferences
*** Base directory
#+begin_src emacs-lisp
  (setq org-directory "~/notes/")
#+end_src

*** Global keys
 #+BEGIN_SRC emacs-lisp
   (bind-key "\C-cl" 'org-store-link)
   (bind-key "\C-cc" 'org-capture)
   (bind-key "\C-ca" 'org-agenda)
   (bind-key "<f12>" 'org-agenda)
   (bind-key "\C-cb" 'org-iswitchb)
 #+END_SRC
*** Custom ellipsis
#+BEGIN_SRC emacs-lisp
(setq org-ellipsis " ⬎") ;; ⤵ ↴ ⬎ ⤷
(set-face-attribute 'org-ellipsis nil :underline nil)
#+END_SRC
** Fancy UI
*** org-bullets
#+BEGIN_SRC emacs-lisp
  (use-package org-bullets
    :hook (org-mode . org-bullets-mode)
    :custom (org-bullets-bullet-list '("◉" "○" "●" "►" "◇" "◎")))
#+END_SRC

Hiding leading bullets in headers

#+begin_src emacs-lisp
  (setq org-hide-leading-stars t)
#+end_src
*** org-fancy-priorities

#+BEGIN_SRC emacs-lisp
  (use-package org-fancy-priorities
        :diminish
        :defines org-fancy-priorities-list
        :hook (org-mode . org-fancy-priorities-mode)
        :config (setq org-fancy-priorities-list '("⚡" "⬆" "⬆" "⬇")))
#+END_SRC

Set colors for priority faces

#+BEGIN_SRC emacs-lisp
  (setq org-lowest-priority ?D
          org-default-priority ?D
          org-priority-faces '((?A . (:foreground "red" :weight bold))
                               (?B . (:foreground "orange"))
                               (?C . (:foreground "yellow"))
                               (?D . (:foreground "green"))))
#+END_SRC

** Org-clock
*** Function for clocking in
#+begin_src emacs-lisp
(defun nc/org-clock-in ()
  (interactive)
  (org-clock-in '(4)))

(global-set-key (kbd "<f11>") #'nc/org-clock-in)
(global-set-key (kbd "C-<f11>") 'org-clock-out)
#+end_src
*** Configuration

Too many clock entries clutter up a heading.

#+begin_src emacs-lisp
  (use-package org
    :bind (("C-c C-x C-i" . nc/org-clock-in)
           ("C-c C-x C-o" . org-clock-out)
           ("M-<f11>" . org-clock-goto))
    :config
    (progn
      ;; Insinuate it everywhere
      (org-clock-persistence-insinuate)
      ;; Show lot of clocking history so it's easy to pick items off the C-F11 list
      (setq org-clock-history-length 23
            ;; Resume clocking task on clock-in if the clock is open
            org-clock-in-resume t
            ;; Separate drawers for clocking and logs
            org-drawers '("PROPERTIES" "CLOCK" "LOGBOOK" "RESULTS" "HIDDEN")
            ;; Save clock data and state changes and notes in the LOGBOOK drawer
            org-clock-into-drawer t
            ;; Sometimes I change tasks I'm clocking quickly -
            ;; this removes clocked tasks with 0:00 duration
            org-clock-out-remove-zero-time-clocks t
            ;; Clock out when moving task to a done state
            org-clock-out-when-done t
            ;; Save the running clock and all clock history when exiting Emacs, load it on startup
            org-clock-persist t
            ;; Prompt to resume an active clock
            org-clock-persist-query-resume t
            ;; Enable auto clock resolution for finding open clocks
            org-clock-auto-clock-resolution #'when-no-clock-is-running
            ;; Include current clocking task in clock reports
            org-clock-report-include-clocking-task t)))
#+end_src

*** Timereport indentation
Fix timereport indentation

#+begin_src emacs-lisp
(defun nc--org-clocktable-indent-string (level)
  (if (= level 1)
      ""
    (let ((str "\\"))
      (while (> level 2)
        (setq level (1- level)
              str (concat str "_")))
      (concat str "_ "))))

(advice-add 'org-clocktable-indent-string :override #'nc--org-clocktable-indent-string)
#+end_src
*** Clock in organization task as default
Organization task ID
#+begin_src emacs-lisp
(defvar nc/organization-task-id "93905237-907b-42a6-bdb1-11832c4d59d5")
#+end_src

This clocks in a predefined task by org-id that is the default task to clock in
#+begin_src emacs-lisp
  (use-package org-id
    :ensure org
    :config
    (defun nc/clock-in-organization-task-as-default ()
      (interactive)
      (org-with-point-at (org-id-find nc/organization-task-id 'marker)
        (org-clock-in '(16)))))
#+end_src


#+begin_src emacs-lisp
  (bind-key "C-<f9>" 'nc/clock-in-organization-task-as-default)
#+end_src
** GTD Workflow
*** Tasks & projects
**** Todo tasks
***** Todo states
  - parentheses indicate keyboard shortcuts
  - =@= prompts for a note
  - =!= logs the timestamp of the state change

 #+BEGIN_SRC emacs-lisp
   (setq org-todo-keywords
    '((sequence "TODO(t)" "NEXT(n)" "SOMEDAY(.)" "MAYBE(M)"  "|" "DONE(d!)")
      (sequence "STARTED(s)" "WAITING(w@/!)" "|" "CANCELLED(c@/!)" "INACTIVE(i@/!)")
      (sequence "MEETING(m)" "RDV(r)"  "|" "DONE(d)")))
 #+END_SRC

***** Todo faces
 Colors from https://flatuicolors.com/

 #+BEGIN_SRC emacs-lisp
   (setq org-todo-keyword-faces
         (quote (("TODO" :foreground "#c0392b" :weight bold)
                 ("NEXT" :foreground "#d35400" :weight bold)
                 ("STARTED" :foreground "#f39c12" :weight bold)
                 ("SOMEDAY" :foreground "#3498db" :weight bold)
                 ("DONE" :foreground "#27ae60" :weight bold)
                 ("WAITING" :foreground "#e74c3c" :weight bold)
                 ("INACTIVE" :foreground "#bdc3c7" :weight bold)
                 ("MEETING" :foreground "#8e44ad" :weight bold)
                 ("RDV" :foreground "#9b59b6" :weight bold)
                 ("MAYBE" :foreground "#3498db" :weight bold)
                 ("CANCELLED" :foreground "#7f8c8d" :weight bold))))
 #+END_SRC
**** Contexts
 #+BEGIN_SRC emacs-lisp
   (setq org-tag-alist (quote (("@computer" . ?c)
                               ("@office" . ?o)
                               ("@home" . ?h)
                               ("@reading" . ?r)
                               ("learning" . ?l)
                               (:newline)
                               ("WAITING" . ?w)
                               ("HOLD" . ?H)
                               ("CANCELLED" . ?c))))

   ;;(setq org-fast-tag-selection-single-key nil)

 #+END_SRC
**** Projects
Projects are marked with the =project= tag. They are supposed to
contain todo items, and are considered stuck unless they do. The
=project= tag should not be inheritable, because otherwise its tasks
will appear as projects.
   #+begin_src emacs-lisp
     (setq org-tags-exclude-from-inheritance '("project" "crypt")
           org-stuck-projects '("+project/-DONE"
                                ("TODO" "NEXT") ()))
   #+end_src

*** Files and directories

 #+begin_src emacs-lisp
   (defconst nc/org-default-projects-dir (concat org-directory "projects"))
   (defconst nc/org-default-projects-file (concat org-directory "projects/tasks.org"))
   (defconst nc/org-default-resources-dir (concat org-directory "resources"))
   (defconst nc/org-default-personal-dir (concat org-directory "personal"))
   (defconst nc/org-default-completed-dir (concat org-directory "projects/_completed"))
   (defconst nc/inbox-file (concat org-directory "inbox.org"))
   (defconst nc/org-default-inbox-file (concat org-directory "inbox.org"))
   (defconst nc/watching-file (concat org-directory "personal/watching.org"))
   (defconst nc/org-default-media-files (concat org-directory "personal/watching.org"))
   (defconst nc/fishing-file (concat org-directory "personal/sports/fishing.org"))
   (defconst nc/someday-file (concat org-directory "projects/someday.org"))
   (defconst nc/calendar-file (concat org-directory "personal/calendar.org"))
   (defconst nc/weekly-review-file (concat org-directory "personal/reviews/weekly-review.org"))
 #+end_src
*** Org Journal
**** Configuration
 #+BEGIN_SRC emacs-lisp
 (use-package org-journal
          :ensure t
           :init
           (setq org-journal-dir "~/notes/journal/")
           (setq org-journal-date-format "%e %b %Y (%A)")
           (setq org-journal-time-format "")
           (setq org-journal-file-format "%Y-%m-%d.org"))
 #+END_SRC

**** Function to easily load today

 #+BEGIN_SRC emacs-lisp
   (defun nc--get-journal-file-today ()
     "Return filename for today's journal entry."
     (let ((daily-name (format-time-string "%Y-%m-%d.org")))
       (expand-file-name (concat org-journal-dir daily-name))))

   (defun nc/journal-file-today ()
     "Create and load a journal file based on today's date."
     (interactive)
     (find-file (nc--get-journal-file-today)))

   (global-set-key (kbd "C-c f j") 'nc/journal-file-today)
 #+END_SRC
**** Yesterday journal file

#+BEGIN_SRC emacs-lisp
  (defun nc--get-journal-file-yesterday ()
    "Return filename for yesterday's journal entry."
    (let* ((yesterday (time-subtract (current-time) (days-to-time 1)))
           (daily-name (format-time-string "%Y-%m-%d.org" yesterday)))
      (expand-file-name (concat org-journal-dir daily-name))))

  (defun nc/journal-file-yesterday ()
    "Creates and load a file based on yesterday's date."
    (interactive)
    (find-file (nc--get-journal-file-yesterday)))

  (global-set-key (kbd "C-c f y") 'nc/journal-file-yesterday)
#+END_SRC

**** Auto Insert
     Insert in journal file
   #+BEGIN_SRC emacs-lisp
     (defun nc/journal-file-insert ()
       "Insert's the journal heading based on the file's name."
       (interactive)
       (let* ((year  (string-to-number (substring (buffer-name) 0 4)))
              (month (string-to-number (substring (buffer-name) 5 7)))
              (day   (string-to-number (substring (buffer-name) 8 10)))
              (datim (encode-time 0 0 0 day month year)))

         (insert (format-time-string (concat "#+TITLE:" org-journal-date-format) datim))
         (insert "\n")

         ;; Note: The `insert-file-contents' leaves the cursor at the
         ;; beginning, so the easiest approach is to insert these files
         ;; in reverse order:

         ;; If the journal entry I'm creating matches today's date:
         (when (equal (file-name-base (buffer-file-name))
                      (format-time-string "%Y-%m-%d"))

           (insert-file-contents "templates/journal-dailies-end.org")


           ;; Insert dailies that only happen once a week:
           (let ((weekday-template (downcase
                                    (format-time-string "templates/journal-%A.org"))))
             (when (file-exists-p weekday-template)
               (insert-file-contents weekday-template)))


           (insert-file-contents "templates/journal-dailies.org")
           (insert "")

           (let ((contents (buffer-string)))
             (delete-region (point-min) (point-max))
             (yas-expand-snippet contents (point-min) (point-max))))
         ))

         ;; bind-key
         (bind-key "C-c o i" 'nc/journal-file-insert)
   #+END_SRC
*** Navigation

#+BEGIN_SRC emacs-lisp
(defun nc/go-to-projects ()
  (interactive)
  (find-file nc/org-default-projects-file )
  (widen)
  (beginning-of-buffer)
  (re-search-forward "* Projects")
  (beginning-of-line))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (defun nc/go-to-resources-dir ()
    (interactive)
    (dired nc/org-default-resources-dir))
#+END_SRC

*** Org default notes file
One default notes files by day in *journal/* folder
#+BEGIN_SRC emacs-lisp
(setq org-default-notes-file (nc--get-journal-file-today))
#+END_SRC

*** Capture templates


 My templates :

 #+begin_src emacs-lisp
 (setq org-capture-templates
         '(("t" "Task" entry (file+headline nc/inbox-file "Inbox" )
            "* TODO %?\n%U\n%a\n" :clock-in t :clock-resume t)
           ("s" "Someday / Maybe" entry (file+headline nc/someday-file "Someday")
             "* SOMEDAY %? :IDEA:\n%u" :clock-in t :clock-resume t)
           ("f" "FishLog" plain (file+datetree+prompt nc/fishing-file)
            "%[~/notes/templates/fishlog.org]")
           ("F" "Film" entry (file+headline nc/watching-file "Films à voir")
                "* NEXT %^{Titre}
        %i
        - *Réalisateur:* %^{Auteur}
        - *Année:* %^{année}
        - *Genre:* %^{genre}

       %?

       %U" :prepend t)


            ("D" "Done Business Task" entry
              (function org-journal-find-location)
              "* DONE %^{Task}"
              :clock-in t :clock-resume t)
           ))
 #+end_src
**** TODO Meeting
 Should be moved in gcal.org

 #+BEGIN_SRC emacs-lisp
 (add-to-list 'org-capture-templates
                  `("m" "Meeting" entry (file+headline nc/calendar-file "Réunions")
            "* MEETING %? :MEETING:\n%U\nSCHEDULED: %(org-insert-time-stamp (org-read-date nil t \"+0d\"))\n"))
 #+END_SRC

**** TODO RendezVous
 Should be moved in gcal.org
 #+BEGIN_SRC emacs-lisp
 (add-to-list 'org-capture-templates
                  `("a" "RendezVous" entry (file+headline nc/calendar-file "RendezVous")
                  "* RDV %? :APPT:\n%U\nSCHEDULED: %(org-insert-time-stamp (org-read-date nil t \"+0d\"))\n"))
 #+END_SRC

**** Journal entry

 Integrate =org-journal= with =org-capture=

 #+BEGIN_SRC emacs-lisp
   (defun org-journal-find-location ()
     ;; Open today's journal, but specify a non-nil prefix argument in order to
     ;; inhibit inserting the heading; org-capture will insert the heading.
     (org-journal-new-entry t)
     ;; Position point on the journal's top-level heading so that org-capture
     ;; will add the new entry as a child entry.
     (goto-char (point-min)))

   (add-to-list 'org-capture-templates
                  `("j" "Journal entry" entry (function org-journal-find-location)
                         "* %?\n  %i\n  From: %a" :empty-lines 1))
 #+END_SRC
**** General Note
#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-capture-templates
                   '("n" "Note"  entry
                     (file nc/inbox-file)
                     "* %?\n\n  %i\n\n  See: %a" :empty-lines 1))
#+END_SRC
**** Interruption task
 #+BEGIN_SRC emacs-lisp
   (add-to-list 'org-capture-templates
                `("i" "Interrupting task" entry
                  (function org-journal-find-location)
                  "* %^{Task}"
                  :clock-in t :clock-resume t))
 #+END_SRC


 #+begin_src emacs-lisp
   (defun my/capture-interruption-task ()
       "Interrupted Task"
       (interactive)
       (org-capture 4 "i"))

   ;; Override the key definition
   (global-set-key (kbd "<f9>") 'my/capture-interruption-task)
 #+end_src
**** New project
I have my own template for creating new projects

#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-capture-templates
                     `("p" "New Project" entry (file+headline nc/org-default-projects-file "Projects")
               (file "~/notes/templates/newproject.org")))
#+END_SRC

**** Daily Review

 #+BEGIN_SRC emacs-lisp
   (add-to-list 'org-capture-templates
                `("d" "Review: Daily Review" entry (function org-journal-find-location)
                  (file "~/notes/templates/dailyreview.org")
                  :clock-in t :clock-resume t))
 #+END_SRC

 #+BEGIN_SRC emacs-lisp
   (defun nc/daily-review ()
         (interactive)
           (progn
             (org-capture nil "d")
             (org-capture-finalize t)
             (org-narrow-to-subtree)
             (org-clock-in)))
 #+END_SRC
**** WeeklyReview
 #+BEGIN_SRC emacs-lisp
 (add-to-list 'org-capture-templates
                  `("w" "WeeklyReview" entry (file+datetree+prompt nc/weekly-review-file)
            "* Summary of the week :REVIEW:\n%[~/notes/templates/review.org]"))
 #+END_SRC
*** Refiling
 Targets include this file and any file contributing to the agenda - up to 3 levels deep
 #+begin_src emacs-lisp
   (setq org-reverse-note-order t)
   (setq org-refile-targets (quote ((nil :maxlevel . 3)
                                    (org-agenda-files :maxlevel . 3))))
   (setq org-blank-before-new-entry nil)
 #+end_src

 Exclude completed tasks from refile targets.

 #+BEGIN_SRC emacs-lisp
   (defun nc--verify-refile-target ()
     "Exclude todo keywords with a done state from refile targets"
     (not (member (nth 2 (org-heading-components)) org-done-keywords)))

   (setq org-refile-target-verify-function 'nc--verify-refile-target)
 #+END_SRC


 Listing filenames and headings in targets and do not complete in steps, helm will listing filenames & headings.

 #+BEGIN_SRC emacs-lisp
 (setq org-refile-use-outline-path 'file)
 (setq org-outline-path-complete-in-steps nil)
 #+END_SRC

 Allow creating parent nodes

 #+BEGIN_SRC emacs-lisp
 (setq org-refile-allow-creating-parent-nodes 'confirm)
 #+END_SRC

**** Searching in my notes
 #+begin_src emacs-lisp
 (defun nc/helm-do-grep-notes ()
   "Search in all my org notes."
   (interactive)
   (helm-do-grep-1 (list org-directory) t nil (list "*.org")))
 #+end_src
*** Agenda
**** Agenda configuration
 By default all files in GTD and journal folder will be in my agenda, to be searchable

 My custom agends commands are restricted to some files.
 #+BEGIN_SRC emacs-lisp
   (setq org-agenda-files (list "~/notes/inbox.org" "~/notes/personal/calendar.org" "~/notes/journal/" "~/notes/projects/")
         org-agenda-span 'day
         org-agenda-start-on-weekday nil
         org-agenda-skip-deadline-if-done t
         org-agenda-skip-scheduled-if-done t
         org-agenda-start-with-log-mode t
         org-agenda-block-separator nil
         org-deadline-warning-days 5)
 #+END_SRC
**** Diary
 #+BEGIN_SRC emacs-lisp
   (setq diary-file "~/notes/diary"
         org-agenda-include-diary t)
 #+END_SRC
**** Custom Agenda commands
***** Function to skip headline tagged with =:project:=

 #+begin_src emacs-lisp
 (defun nc--org-agenda-skip-project ()
     (org-agenda-skip-entry-if 'regexp ":project:"))
 #+end_src

***** Display Header parent

 #+BEGIN_SRC emacs-lisp
 (defun nc--org-agenda-format-parent (n)
   ;; (s-truncate n (org-format-outline-path (org-get-outline-path)))
   (save-excursion
     (save-restriction
       (widen)
       (org-up-heading-safe)
       (s-truncate n (org-get-heading t t)))))
 #+END_SRC
***** Agenda Commands

     #+BEGIN_SRC emacs-lisp
       (defun org-current-is-todo ()
         (string= "NEXT" (org-get-todo-state)))

       (defun org-agenda-skip-all-siblings-but-first ()
         "Skip all but the first non-done entry."
         (let (should-skip-entry)
           (unless (org-current-is-todo)
             (setq should-skip-entry t))
           (save-excursion
             (while (and (not should-skip-entry) (org-goto-sibling t))
               (when (org-current-is-todo)
                 (setq should-skip-entry t))))
           (when should-skip-entry
             (or (outline-next-heading)
                 (goto-char (point-max))))))

       (require 'org-agenda)

       (setq org-agenda-custom-commands
             '((" " "Agenda"
                      ((agenda "" ((org-agenda-sorting-strategy '(timestamp-up time-up priority-down category-keep))))

                       (tags-todo "TODO=\"STARTED\"+@office|TODO=\"WAITING\"+@office"
                                  ((org-agenda-overriding-header "Started / waiting tasks @office")
                                   (org-agenda-prefix-format "%-27:(nc--org-agenda-format-parent 25)")
                                   (org-agenda-sorting-strategy '(priority-down todo-state-up category-keep))))
                       ;; (tags-todo "TODO=\"NEXT\"+@office-HOLD"
                       ;;            ((org-agenda-overriding-header "Next tasks @office")
                       ;;             (org-tags-exclude-from-inheritance '("project"))
                       ;;             (org-agenda-prefix-format "%-27:(nc--org-agenda-format-parent 25)")
                       ;;             ;; (org-agenda-skip-function
                       ;;             ;;  (quote
                       ;;             ;;   (org-agenda-skip-all-siblings-but-first)))
                       ;;             (org-agenda-sorting-strategy '(priority-down todo-state-up category-keep))
                       ;;             (org-agenda-todo-keyword-format "%-4s")))
                       (tags-todo "TODO=\"TODO\"-HOLD"
                                  ((org-agenda-overriding-header "Other tasks")
                                   (org-agenda-prefix-format "%-27:(nc--org-agenda-format-parent 30)")
                                   (org-agenda-skip-function
                                    '(org-agenda-skip-entry-if 'scheduled 'deadline))
                                   (org-agenda-files '("~/notes/inbox.org"))
                                   (org-agenda-sorting-strategy '(priority-down todo-state-up category-keep))))
                       )
                      nil)
               ("g" . "GTD contexts")
                  ("go" "Office" tags-todo "@office")
                  ("gc" "Computer" tags-todo "@computer")
                  ("ge" "Emacs" tags-todo "emacs")
                  ("gl" "Learning" tags-todo "learning")
                  ("gr" "Reading" tags-todo "@reading")
                   ;; exports block to this file with C-c a e
                 ;; ..other commands here

                  ))
     #+END_SRC
**** Recent open loops

 #+BEGIN_SRC emacs-lisp
 (defun nc/org-agenda-recent-open-loops ()
     (interactive)
     (let ((org-agenda-start-with-log-mode t)
             (org-agenda-use-time-grid nil))
       ;; (fetch-calendar)
       (org-agenda-list nil (org-read-date nil nil "-2d") 4)))
 #+END_SRC
** Speed commands
 From https://orgmode.org/worg/org-hacks.html
 #+BEGIN_SRC emacs-lisp
     (defun nc/org-show-next-heading-tidily ()
       "Show next entry, keeping other entries closed."
       (if (save-excursion (end-of-line) (outline-invisible-p))
           (progn (org-show-entry) (show-children))
         (outline-next-heading)
         (unless (and (bolp) (org-on-heading-p))
           (org-up-heading-safe)
           (hide-subtree)
           (error "Boundary reached"))
         (org-overview)
         (org-reveal t)
         (org-show-entry)
         (show-children)))

     (defun nc/org-show-previous-heading-tidily ()
       "Show previous entry, keeping other entries closed."
       (let ((pos (point)))
         (outline-previous-heading)
         (unless (and (< (point) pos) (bolp) (org-on-heading-p))
           (goto-char pos)
           (hide-subtree)
           (error "Boundary reached"))
         (org-overview)
         (org-reveal t)
         (org-show-entry)
         (show-children)))

     (setq org-use-speed-commands t)

   (setq org-use-speed-commands
         (lambda () (and (looking-at org-outline-regexp) (looking-back "^\**"))))

   (setq org-speed-commands-user
         '(("n" nc/org-show-next-heading-tidily)
           ("p" nc/org-show-previous-heading-tidily)
           ("N" org-narrow-to-subtree)
           ("$" org-archive-subtree)
           ("A" org-archive-subtree)
           ("W" widen)
           ("d" org-down-element)
           ("k" org-cut-subtree)
           ("m" org-mark-subtree)
           ("s" org-sort)
           ("X" org-todo-done)
           ("R" org-done-and-archive)
           ("y" org-todo-yesterday)))
 #+END_SRC

** Publishing my notes
*** Table Of Contents
 Only 2 levels
#+begin_src emacs-lisp
  (setq org-export-with-toc 2)
#+end_src
*** Basic Configuration
    - Headings starts with =<h2>= and with no section numbers.

  #+BEGIN_SRC emacs-lisp
    (setq org-html-toplevel-hlevel 2)
    (setq org-export-with-section-numbers nil)
    (setq org-export-with-sub-superscripts nil)
  #+END_SRC
*** CSS Style

#+begin_src emacs-lisp
  ;; (setq org-html-head "<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Inconsolata\">
  ;; <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">")
  (setq org-html-head "<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">")
#+end_src

*** Publishing projects

 #+BEGIN_SRC emacs-lisp
   (setq org-publish-project-alist
         '(("GTD"
            :base-directory "~/notes/GTD"
            :exclude "diary-log.org\\|calendar.org"
            :publishing-directory "~/Public/html"
            :publishing-function org-html-publish-to-html
            )
           ("org-static"
            :base-directory "~/notes/publish"
            :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf\\|mp3\\|ogg\\|swf"
            :publishing-directory "~/Public/html"
            :recursive t
            :publishing-function org-publish-attachment
            )))
 #+END_SRC

** Babel
*** Babel languages

#+begin_src emacs-lisp
  (use-package ob-restclient)

  (setq org-plantuml-jar-path
        (expand-file-name "~/opt/lib/plantuml.jar"))

  (org-babel-do-load-languages
   'org-babel-load-languages
   '((shell . t)
     (python . t)
     (calc . t)
     (js . t)
     (plantuml . t)
     (dot . t)
     (restclient . t)))
#+end_src
*** Editing source code
 I don't want to get distracted by the same code in the other window, so I want org src to use the current window.

 #+begin_src emacs-lisp
   (setq org-src-window-setup 'current-window)
 #+end_src
*** Evaluate code blocks without prompting
#+begin_src emacs-lisp
  (setq org-confirm-babel-evaluate nil)
#+end_src
*** Syntax highlight in source blocks
#+begin_src emacs-lisp
  (setq org-src-fontify-natively t)
#+end_src
** Habits
#+begin_src emacs-lisp
(require 'org-habit)
(add-to-list 'org-modules "org-habit")
(setq org-habit-preceding-days 7
      org-habit-following-days 1
      org-habit-graph-column 80
      org-habit-show-habits-only-for-today t
      org-habit-show-all-today t)
#+end_src
** Org Crypt
#+begin_src emacs-lisp
  (require 'org-crypt)
  (org-crypt-use-before-save-magic)

  ;; (setq org-tags-exclude-from-inheritance (quote ("crypt")))
  ;; GPG key to use for encryption
  ;; Either the Key ID or set to nil to use symmetric encryption.
  (setq org-crypt-key nil)
#+end_src
** ox-pandoc
Export Org documents via Pandoc
#+begin_src emacs-lisp
(use-package ox-pandoc
  :ensure t
  :config
  ;; Use external css for html5
  (let ((stylesheet (expand-file-name
                     (locate-user-emacs-file "etc/pandoc.css"))))
    (setq org-pandoc-options-for-html5
`((css . ,(concat "file://" stylesheet))))))
#+end_src

#+BEGIN_SRC emacs-lisp
(use-package htmlize
  :commands (htmlize-buffer
             htmlize-file
             htmlize-many-files
             htmlize-many-files-dired
             htmlize-region))
#+END_SRC
** Yankpad
#+BEGIN_SRC emacs-lisp
  (use-package yankpad
    :ensure t
    :defer 10
    :init
    (setq yankpad-file "~/notes/templates/yankpad.org")
    :config
    (bind-key "<f7>" 'yankpad-map)
    ;(bind-key "<f12>" 'yankpad-expand)
    ;; If you want to complete snippets using company-mode
    ;;(add-to-list 'company-backends #'company-yankpad)
    ;; If you want to expand snippets with hippie-expand
    (add-to-list 'hippie-expand-try-functions-list #'yankpad-expand))
#+END_SRC
* Tools
** Deft -> <F8>
#+BEGIN_SRC emacs-lisp
  (use-package deft
      :bind
      (("<f8>" . deft))
      :config
      (setq deft-directory "~/notes"
            deft-recursive t
            deft-extensions '("org")
            deft-default-extension "org"
            deft-text-mode 'org-mode
            deft-org-mode-title-prefix t
            deft-use-filter-string-for-filename t
            deft-auto-save-interval 0
            deft-recursive-ignore-dir-regexp
              (concat "\\(?:"
                      "\\."
                      "\\|\\.\\."
                      "\\\|valtech"
                      "\\|journal"
                      "\\)$")
            deft-file-naming-rules
              '((noslash . "-")
                (nospace . "-")
                (case-fn . downcase))))
#+END_SRC
** Docker
#+begin_src emacs-lisp
  (use-package dockerfile-mode
    :mode "Dockerfile.*\\'")
#+end_src
** PDF
#+begin_src emacs-lisp
  (use-package pdf-tools
    :ensure t
    :config
    (pdf-tools-install)
    (setq-default pdf-view-display-size 'fit-page)
    (use-package org-pdfview
      :ensure t))
#+end_src

** Magit

#+BEGIN_QUOTE
Magit a git porcelain inside Emacs !

[[https://github.com/magit/magit]]
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
  (use-package magit
    :bind (("C-x g" . magit-status)
           ("<f6>" . magit-status )
           ("C-<f6>" . magit-log-buffer-file)))
#+END_SRC
** Shells
*** Eshell
    Mainly come from [[https://github.com/howardabrams/dot-files/blob/master/emacs-eshell.org]]
**** Configuration

 #+begin_src emacs-lisp
   (use-package eshell
     :init
     (setq eshell-scroll-to-bottom-on-input 'all
           eshell-error-if-no-glob t
           eshell-hist-ignoredups t
           eshell-save-history-on-exit t
           ;;eshell-prefer-lisp-functions nil
           eshell-destroy-buffer-when-process-dies t)

     )
 #+end_src
**** Visual commands

 #+begin_src emacs-lisp
   (use-package eshell
     :init
     (require 'em-term)
     (setq eshell-visual-commands '("vi" "screen" "top" "less" "more" "lynx"
                                    "ncftp" "pine" "tin" "trn" "elm" "htop" "node" "npm")
           eshell-visual-subcommands '(("git" "log" "diff" "show"))))
 #+end_src

**** Aliases

 #+begin_src emacs-lisp
   (add-hook 'eshell-mode-hook (lambda ()
       (eshell/alias "e" "find-file $1")
       (eshell/alias "f" "helm-find-files $1")
       (eshell/alias "p" "helm-projectile")
       (eshell/alias "esudo" "find-file /sudo::/$1")
       (eshell/alias "emacs" "find-file $1")
       (eshell/alias "ee" "find-file-other-window $1")

       (eshell/alias "gd" "magit-diff-unstaged")
       (eshell/alias "gds" "magit-diff-staged")
       (eshell/alias "d" "dired $1")

       (eshell/alias "mvnci" "mvn clean install")
       (eshell/alias "mvncist" "mvn clean install -DskipTests")
       (eshell/alias "mvnist" "mvn install -DskipTests")
       (eshell/alias "git" "git --no-pager $*")

       ;; alias dpsa docker ps -a --format "{{.Names}} {{.Size}} : {{.Command}}" --no-trunc

       ;; The 'ls' executable requires the Gnu version on the Mac
       ;; (eshell/alias "ll" " ls -AlohG")
       ))
 #+end_src

**** Functions
***** Clear buffer
  #+begin_src emacs-lisp
    (defun nc/eshell-clear-buffer ()
      "Clear terminal"
      (interactive)
      (let ((inhibit-read-only t))
        (erase-buffer)
        (eshell-send-input)))

    (add-hook 'eshell-mode-hook
              '(lambda()
                 (local-set-key (kbd "C-l") 'nc/eshell-clear-buffer)))
  #+end_src
***** Exit
      Exit eshell with  =C-d=
 #+BEGIN_SRC emacs-lisp
 (use-package eshell
   :config
   (defun nc/eshell-quit-or-delete-char (arg)
     (interactive "p")
     (if (and (eolp) (looking-back eshell-prompt-regexp))
         (progn
           (eshell-life-is-too-much) ; Why not? (eshell/exit)
           (ignore-errors
             (delete-window)))
       (delete-forward-char arg)))
   :init
   (add-hook 'eshell-mode-hook
             (lambda ()
               (bind-keys :map eshell-mode-map
                          ("C-d" . nc/eshell-quit-or-delete-char)))))
 #+END_SRC

**** Eshell here

 Opens up a new shell in the directory associated with the
 current buffer's file. The eshell is renamed to match that
 directory to make multiple eshell windows easier.
 #+begin_src emacs-lisp
   (defun nc--eshell-buffer-id ()
     "Next eshell buffer id."
     (let* ((p-lst (split-string (nc--eshell-path-of-current-dir) "/"))
            (name  (mapconcat (lambda (elm) elm) (last p-lst 3) "/")))
       (concat "*eshell: " name "*")))

   (defun nc--eshell-path-of-current-dir ()
     (file-name-directory (or (buffer-file-name) default-directory)))

   (defun nc/eshell-here ()
     "Start, or switch to, `eshell' in the current working directory."
     (interactive)
     (let ((buffer-id (nc--eshell-buffer-id)))
       (cond ((get-buffer buffer-id)
              (switch-to-buffer-other-window buffer-id))
             (t (progn
                  (eshell buffer-id)
                  (rename-buffer buffer-id))))))

   (bind-key "C-c e" 'nc/eshell-here)
 #+end_src

**** Customize eshell prompt
 Add git status in prompt
 #+begin_src emacs-lisp
   (setq eshell-prompt-function
         (lambda ()
           (concat (propertize (abbreviate-file-name (eshell/pwd)) 'face 'eshell-prompt)
                   (when (fboundp #'vc-git-branches)
                     (let ((branch (car (vc-git-branches))))
                       (when branch
                         (concat
                          (propertize " [" 'face 'font-lock-keyword-face)
                          (propertize branch 'face 'font-lock-function-name-face)
                          (let* ((status (shell-command-to-string "git status --porcelain"))
                                 (parts (split-string status "\n" t " "))
                                 (states (mapcar #'string-to-char parts))
                                 (added (cl-count-if (lambda (char) (= char ?A)) states))
                                 (modified (cl-count-if (lambda (char) (= char ?M)) states))
                                 (deleted (cl-count-if (lambda (char) (= char ?D)) states)))
                            (when (> (+ added modified deleted) 0)
                              (propertize (format " +%d ~%d -%d" added modified deleted) 'face 'font-lock-comment-face)))
                          (propertize "]" 'face 'font-lock-keyword-face)))))
                   (propertize " $ " 'face 'font-lock-constant-face))))
 #+end_src
**** Eshell History
 Using Helm with =C-c C-l= to browse eshell history
 #+begin_src emacs-lisp
   (require 'helm-eshell)

   (add-hook 'eshell-mode-hook
             #'(lambda ()
                 (define-key eshell-mode-map (kbd "C-c C-l")  'helm-eshell-history)))
 #+end_src
**** Fish like auto completion
     Provides a company backend that implements functionality similar to
     fish shell history autosuggestions.
 #+begin_src emacs-lisp
   (use-package esh-autosuggest
     :config (add-hook 'eshell-mode-hook #'esh-autosuggest-mode))
 #+end_src
*** Shell
**** helm-comint-input-ring
 Similar to =helm-eshell-history=, but used for =M-x shell=.

 #+begin_src emacs-lisp
   (define-key shell-mode-map (kbd "C-c C-l") 'helm-comint-input-ring)
 #+end_src
**** Better Shell

 Simplifies shell management
 #+begin_src emacs-lisp
   (use-package better-shell
       :ensure t
       :bind (("C-'" . better-shell-shell)
              ("C-;" . better-shell-remote-open)
              ("M-<f12>" . better-shell-for-current-dir)))
 #+end_src
*** Ansi Terminal Emulator
Sometimes I need an Ansi Term...
**** Force Bash
#+BEGIN_SRC emacs-lisp
  (defconst t-term-name "/bin/bash")

  (defadvice ansi-term (before force-bash)
        (interactive (list t-term-name)))

  (ad-activate 'ansi-term)
#+END_SRC
**** Kill buffer on exit
#+BEGIN_SRC emacs-lisp
  (defun nc--ansi-term-mode-hook ()
    "Close current term buffer when `exit' or c-d from term buffer."
    (goto-address-mode)

    (when (ignore-errors (get-buffer-process (current-buffer)))
      (set-process-sentinel
       (get-buffer-process (current-buffer))
       (lambda (proc change)
         (message change)
         (when (string-match "\\(finished\\|exited\\)" change)
           (kill-buffer (process-buffer proc)))))))

  (add-hook 'term-mode-hook #'nc--ansi-term-mode-hook)
#+END_SRC

**** Bind Key
#+BEGIN_SRC emacs-lisp
(bind-key "C-c t" 'ansi-term)
#+END_SRC

* Programming
** asciidoc

#+BEGIN_SRC emacs-lisp
  (use-package adoc-mode
    :ensure t
    :mode "\\.adoc?\\'")
#+END_SRC

** Go
Go mode needs some go tools
*** Go Imports
    #+BEGIN_EXAMPLE
    go get golang.org/x/tools/cmd/goimports
    #+END_EXAMPLE
*** Gocode
    For completion
#+BEGIN_EXAMPLE
go get -u github.com/nsf/gocode
#+END_EXAMPLE
*** Godef
    #+BEGIN_EXAMPLE
    go get github.com/rogpeppe/godef
    #+END_EXAMPLE
*** Go mode setup

Then we can setup Emacs go mode

#+begin_src emacs-lisp
  (use-package go-mode
    :config
    ; Use goimports instead of go-fmt
    (setq gofmt-command "goimports")
    (add-hook 'go-mode-hook 'company-mode)
    ;; Call Gofmt before saving
    (add-hook 'before-save-hook 'gofmt-before-save)
    (add-hook 'go-mode-hook 'nc--setup-go-mode-compile)
    (add-hook 'go-mode-hook #'smartparens-mode)
    (add-hook 'go-mode-hook '(lambda ()
                   (local-set-key (kbd "C-c C-r") 'go-remove-unused-imports)))
    (add-hook 'go-mode-hook '(lambda ()
                   (local-set-key (kbd "C-c C-g") 'go-goto-imports)))
    (add-hook 'go-mode-hook (lambda ()
                  (set (make-local-variable 'company-backends) '(company-go))
                  (company-mode)))
    :bind (:map go-mode-map
                ("C-c C-t s" . nc/test-single)
                ("C-c C-t a" . nc/test-all)
                ("C-c C-t n" . nc/test-nested)))


  (defun nc--run-tests (args)
    (save-selected-window
      (async-shell-command (concat "go test -v " args))))

  (defun nc/test-all ()
    (interactive)
    (nc--run-tests ""))

  (defun nc/test-nested ()
    (interactive)
    (nc--run-tests "./..."))

  (defun nc/test-single ()
    (interactive)
    (if (string-match "_test\\.go" buffer-file-name)
        (save-excursion
          (re-search-backward "^func[ ]+\\(([[:alnum:]]*?[ ]?[*]?[[:alnum:]]+)[ ]+\\)?\\(Test[[:alnum:]_]+\\)(.*)")
          (nc--run-tests (concat "-run" "='" (match-string-no-properties 2) "'")))
      (error "Must be in a _test.go file")))

  (use-package company-go
    :after go-mode
    :config
    (setq tab-width 4)

    :bind (:map go-mode-map
    ; Godef jump key binding
    ("M-." . godef-jump)))

  (use-package flymake-go)

  (use-package go-eldoc
    :config
    (add-hook 'go-mode-hook 'go-eldoc-setup))

  (defun nc--setup-go-mode-compile ()
    ; Customize compile command to run go build
    (if (not (string-match "go" compile-command))
        (set (make-local-variable 'compile-command)
             "go build -v && go test -v && go vet")))

  (defun nc/go-run()
    "Compile and run my program"
    (interactive)
    (save-some-buffers t)
    (compile "bash -c 'go install && go build -o /tmp/a.out && /tmp/a.out'")
    (end-of-line-compile))

#+end_src
** Lua
#+BEGIN_SRC emacs-lisp
(use-package lua-mode
  :ensure t
  :mode "\\.lua\\'")
#+END_SRC
** Markdown
   GitHub Flavored Markdown by default for README.md files.
#+BEGIN_SRC emacs-lisp
  (use-package markdown-mode
    :mode (("README\\.md\\'" . gfm-mode)
           ("\\.md\\'"       . markdown-mode)
           ("\\.markdown\\'" . markdown-mode))
    :config
    ;; Process Markdown with Pandoc, using GitHub stylesheet for nice output
    (let ((stylesheet (expand-file-name
                       (locate-user-emacs-file "etc/pandoc.css"))))
      (setq markdown-command
            (mapconcat #'shell-quote-argument
                       `("pandoc" "--toc" "--section-divs"
                         "--css" ,(concat "file://" stylesheet)
                         "--standalone" "-f" "markdown" "-t" "html5")
                       " "))))
#+END_SRC

#+RESULTS:
** Rust
#+BEGIN_SRC emacs-lisp
(use-package rust-mode                  ; Rust major mode
  :ensure t
  :bind (:map rust-mode-map ("C-c <tab>" . rust-format-buffer)))

(use-package racer                      ; Completion and navigation for Rust
  :ensure t
  :bind (:map racer-mode-map
              ("C-c m h" . racer-describe)
              ("C-c m d" . racer-debug))
  :hook (rust-mode . racer-mode)
  :config (setq racer-rust-src-path (getenv "RUST_SRC_PATH")))

(use-package cargo                      ; Control Cargo
  :ensure t
  :bind (:map rust-mode-map
              ("<f6>" . cargo-process-build))
  :hook (rust-mode . cargo-minor-mode))

(use-package toml-mode                  ; Toml for Cargo files
  :ensure t
  :defer t)
#+END_SRC

** Smart Comments
Smarter commenting for emacs
#+BEGIN_SRC emacs-lisp
(use-package smart-comment
  :bind ("M-;" . smart-comment))
#+END_SRC

** Smartparens

Smart parens for all modes.

#+BEGIN_SRC emacs-lisp
    (use-package smartparens
      :defer t
      :diminish ""
      :init
      (progn
        (add-hook 'prog-mode-hook #'turn-on-smartparens-mode)
        ;; turn on showing the match for clojure and elisp
        (add-hook 'clojure-mode-hook #'turn-on-show-smartparens-mode)
        (add-hook 'emacs-lisp-mode-hook #'turn-on-show-smartparens-mode)
        (add-hook 'java-mode-hook #'turn-on-show-smartparens-mode)
        (add-hook 'c-mode-hook #'turn-on-show-smartparens-mode))
      :config
      (setq-default sp-hybrid-kill-entire-symbol nil)

      (setq sp-highlight-pair-overlay nil)

      (define-key sp-keymap (kbd "<delete>") 'sp-delete-char)
      (define-key sp-keymap (kbd "C-<right>") 'sp-forward-slurp-sexp)
      (define-key sp-keymap (kbd "C-<left>") 'sp-forward-barf-sexp)
      (define-key sp-keymap (kbd "C-S-<right>") 'sp-backward-barf-sexp)
      (define-key sp-keymap (kbd "C-S-<left>") 'sp-backward-slurp-sexp)
      (define-key sp-keymap (kbd "M-s") 'sp-unwrap-sexp)
      (define-key sp-keymap (kbd "M-S-s") 'sp-raise-sexp)
      (define-key sp-keymap (kbd "M-i") 'sp-split-sexp)
      (define-key sp-keymap (kbd "M-S-i") 'sp-join-sexp)
      (define-key sp-keymap (kbd "M-t") 'sp-transpose-sexp)
      (define-key sp-keymap (kbd "M-S-<left>") 'sp-backward-sexp)
      (define-key sp-keymap (kbd "M-S-<right>") 'sp-forward-sexp)



      (defun nc--create-newline-and-enter-sexp (&rest _ignored)
        "Open a new brace or bracket expression, with relevant newlines and indent. "
        (newline)
        (indent-according-to-mode)
        (forward-line -1)
        (indent-according-to-mode))

      (sp-with-modes '(c-mode c++-mode js-mode js2-mode java-mode
                              typescript-mode perl-mode)
        (sp-local-pair "{" nil :post-handlers
                       '((nc--create-newline-and-enter-sexp "RET")))))
#+END_SRC
** Web
*** Yaml modes
#+BEGIN_SRC emacs-lisp
(use-package yaml-mode)
#+END_SRC
*** Rest Client
#+begin_src emacs-lisp
  (use-package restclient
    :mode (("\\.restclient\\'" . restclient-mode)
           ("\\.http\\'" . restclient-mode)))
#+end_src
*** Vue mode
    Major mode for vue.js development
#+BEGIN_SRC emacs-lisp
  (use-package vue-mode)
#+END_SRC

*** Web Mode

#+begin_src emacs-lisp
  (use-package web-mode
    :ensure t
    :config
    (add-to-list 'auto-mode-alist '("\\.html\\'" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.hbs\\'" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.tag$" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.ftl$" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.jsp$" . web-mode))
    (add-to-list 'auto-mode-alist '("\\.php$" . web-mode))
    (add-hook 'web-mode-hook (lambda ()
                               (setq web-mode-markup-indent-offset 4)
                               (setq web-mode-code-indent-offset 4))))
#+end_src
*** Javascript
**** JS2 Mode
#+begin_src emacs-lisp
  (use-package js2-mode
    :init
    (add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
    (defalias 'javascript-generic-mode 'js2-mode)
    :config
    (js2-imenu-extras-setup)
    (setq-default js-auto-indent-flag nil
                  js2-strict-missing-semi-warning nil
                  js-indent-level 2)

    ;; Don't override global M-j keybinding (join lines)
    (define-key js2-mode-map (kbd "M-j") nil))
#+end_src
**** Code completion with tern
Use tern to add Javascript completion and more...

*tern* should be installed before with npm

#+BEGIN_EXAMPLE
npn install -g tern
#+END_EXAMPLE


#+begin_src emacs-lisp
  (use-package tern
    :ensure t)

  (use-package company-tern
    :ensure    company-tern
    :init      (add-to-list 'company-backends 'company-tern)
    :config    (add-hook 'js2-mode-hook 'tern-mode))
#+end_src

*** TypeScript

#+begin_src emacs-lisp
  (use-package tide
    :ensure t
    :mode ("\\.ts\\'" . typescript-mode))
#+end_src

* Utilities Functions
** Pseudo uuid

Generate a 32 random pseudo uuid

#+begin_src emacs-lisp

  (defun nc--random-alnum ()
    (let* ((alnum "abcdef0123456789")
           (i (% (abs (random)) (length alnum))))
      (substring alnum i (1+ i))))

  (defun nc/uuid ()
    (interactive)
    (dotimes (i 32) (insert (nc--random-alnum))))

#+end_src
** Password generator
Generates a strong password

 #+BEGIN_SRC emacs-lisp

   (defun nc--random-char ()
       (let* ((alnum "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-/%+*?&#[]()={}_<>!$,;:^µ0123456789")
              (i (% (abs (random)) (length alnum))))
         (substring alnum i (1+ i))))


   (defun nc/generate-password ()
       (interactive)
       (dotimes (i 12) (insert (nc--random-char))))
 #+END_SRC
** TimeSlot
Insert time slot mainly used when I schedule meeting or appointment.
#+begin_src emacs-lisp
  (defvar current-hour-format "%H:00")

  (defun nc/insert-time-slot ()
    "Insert Time Slot"
    (interactive)
    (let ((begin (format-time-string current-hour-format (current-time)))
          (end (format-time-string current-hour-format (time-add (current-time) (seconds-to-time 3600)))))
      (insert (concat begin "-" end))))
#+end_src
** Inserting time stamps
   From : https://github.com/novoid/dot-emacs/blob/master/config.org#inserting-time-stamps--my-map-ddtt

#+BEGIN_SRC emacs-lisp
   (defun nc/insert-datestamp()
     "Insert the current date in yyyy-mm-dd format."
     (interactive "*")
     (if (eq major-mode 'org-mode)
         (progn
           (org-insert-time-stamp nil nil nil)
           (insert " "))
         (insert (format-time-string "%Y-%m-%d" (current-time)))))
 #+END_SRC


 #+BEGIN_SRC emacs-lisp
   (defun nc/insert-datestamp-inactive()
     "Insert the current date in yyyy-mm-dd format."
     (interactive "*")
     (if (eq major-mode 'org-mode)
         (progn
       (org-insert-time-stamp nil nil t)
       (insert " "))
       (insert (format-time-string "%Y-%m-%d" (current-time)))))
 #+END_SRC


* Notes
** Inspiration configs
  - https://writequit.org/org/settings.html
  - https://github.com/yveszoundi/emacs.d/blob/master/bootstrap/startup.org
  - https://github.com/rememberYou/.emacs.d
